
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Users: 'Users',
  MajorAccess: 'MajorAccess',
  Majors: 'Majors',
  Criteria: 'Criteria',
  FileLink: 'FileLink',
  Files: 'Files',
  ActivityLogs: 'ActivityLogs',
  AIChatHistory: 'AIChatHistory'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "users" | "majorAccess" | "majors" | "criteria" | "fileLink" | "files" | "activityLogs" | "aIChatHistory"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Users: {
      payload: Prisma.$UsersPayload<ExtArgs>
      fields: Prisma.UsersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findFirst: {
          args: Prisma.UsersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        findMany: {
          args: Prisma.UsersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>[]
        }
        create: {
          args: Prisma.UsersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        createMany: {
          args: Prisma.UsersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.UsersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        update: {
          args: Prisma.UsersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        deleteMany: {
          args: Prisma.UsersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.UsersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.UsersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
    MajorAccess: {
      payload: Prisma.$MajorAccessPayload<ExtArgs>
      fields: Prisma.MajorAccessFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MajorAccessFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MajorAccessFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        findFirst: {
          args: Prisma.MajorAccessFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MajorAccessFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        findMany: {
          args: Prisma.MajorAccessFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>[]
        }
        create: {
          args: Prisma.MajorAccessCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        createMany: {
          args: Prisma.MajorAccessCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.MajorAccessDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        update: {
          args: Prisma.MajorAccessUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        deleteMany: {
          args: Prisma.MajorAccessDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MajorAccessUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.MajorAccessUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorAccessPayload>
        }
        aggregate: {
          args: Prisma.MajorAccessAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMajorAccess>
        }
        groupBy: {
          args: Prisma.MajorAccessGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MajorAccessGroupByOutputType>[]
        }
        count: {
          args: Prisma.MajorAccessCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MajorAccessCountAggregateOutputType> | number
        }
      }
    }
    Majors: {
      payload: Prisma.$MajorsPayload<ExtArgs>
      fields: Prisma.MajorsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MajorsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MajorsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        findFirst: {
          args: Prisma.MajorsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MajorsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        findMany: {
          args: Prisma.MajorsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>[]
        }
        create: {
          args: Prisma.MajorsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        createMany: {
          args: Prisma.MajorsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.MajorsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        update: {
          args: Prisma.MajorsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        deleteMany: {
          args: Prisma.MajorsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MajorsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.MajorsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MajorsPayload>
        }
        aggregate: {
          args: Prisma.MajorsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMajors>
        }
        groupBy: {
          args: Prisma.MajorsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MajorsGroupByOutputType>[]
        }
        count: {
          args: Prisma.MajorsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MajorsCountAggregateOutputType> | number
        }
      }
    }
    Criteria: {
      payload: Prisma.$CriteriaPayload<ExtArgs>
      fields: Prisma.CriteriaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CriteriaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CriteriaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        findFirst: {
          args: Prisma.CriteriaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CriteriaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        findMany: {
          args: Prisma.CriteriaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>[]
        }
        create: {
          args: Prisma.CriteriaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        createMany: {
          args: Prisma.CriteriaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.CriteriaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        update: {
          args: Prisma.CriteriaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        deleteMany: {
          args: Prisma.CriteriaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CriteriaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.CriteriaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CriteriaPayload>
        }
        aggregate: {
          args: Prisma.CriteriaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCriteria>
        }
        groupBy: {
          args: Prisma.CriteriaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CriteriaGroupByOutputType>[]
        }
        count: {
          args: Prisma.CriteriaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CriteriaCountAggregateOutputType> | number
        }
      }
    }
    FileLink: {
      payload: Prisma.$FileLinkPayload<ExtArgs>
      fields: Prisma.FileLinkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FileLinkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FileLinkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        findFirst: {
          args: Prisma.FileLinkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FileLinkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        findMany: {
          args: Prisma.FileLinkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>[]
        }
        create: {
          args: Prisma.FileLinkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        createMany: {
          args: Prisma.FileLinkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.FileLinkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        update: {
          args: Prisma.FileLinkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        deleteMany: {
          args: Prisma.FileLinkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FileLinkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.FileLinkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FileLinkPayload>
        }
        aggregate: {
          args: Prisma.FileLinkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFileLink>
        }
        groupBy: {
          args: Prisma.FileLinkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileLinkGroupByOutputType>[]
        }
        count: {
          args: Prisma.FileLinkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FileLinkCountAggregateOutputType> | number
        }
      }
    }
    Files: {
      payload: Prisma.$FilesPayload<ExtArgs>
      fields: Prisma.FilesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FilesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FilesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        findFirst: {
          args: Prisma.FilesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FilesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        findMany: {
          args: Prisma.FilesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>[]
        }
        create: {
          args: Prisma.FilesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        createMany: {
          args: Prisma.FilesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.FilesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        update: {
          args: Prisma.FilesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        deleteMany: {
          args: Prisma.FilesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FilesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.FilesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilesPayload>
        }
        aggregate: {
          args: Prisma.FilesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFiles>
        }
        groupBy: {
          args: Prisma.FilesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FilesGroupByOutputType>[]
        }
        count: {
          args: Prisma.FilesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FilesCountAggregateOutputType> | number
        }
      }
    }
    ActivityLogs: {
      payload: Prisma.$ActivityLogsPayload<ExtArgs>
      fields: Prisma.ActivityLogsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ActivityLogsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ActivityLogsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        findFirst: {
          args: Prisma.ActivityLogsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ActivityLogsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        findMany: {
          args: Prisma.ActivityLogsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>[]
        }
        create: {
          args: Prisma.ActivityLogsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        createMany: {
          args: Prisma.ActivityLogsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ActivityLogsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        update: {
          args: Prisma.ActivityLogsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        deleteMany: {
          args: Prisma.ActivityLogsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ActivityLogsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ActivityLogsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActivityLogsPayload>
        }
        aggregate: {
          args: Prisma.ActivityLogsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateActivityLogs>
        }
        groupBy: {
          args: Prisma.ActivityLogsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ActivityLogsGroupByOutputType>[]
        }
        count: {
          args: Prisma.ActivityLogsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ActivityLogsCountAggregateOutputType> | number
        }
      }
    }
    AIChatHistory: {
      payload: Prisma.$AIChatHistoryPayload<ExtArgs>
      fields: Prisma.AIChatHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AIChatHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AIChatHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        findFirst: {
          args: Prisma.AIChatHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AIChatHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        findMany: {
          args: Prisma.AIChatHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>[]
        }
        create: {
          args: Prisma.AIChatHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        createMany: {
          args: Prisma.AIChatHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.AIChatHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        update: {
          args: Prisma.AIChatHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        deleteMany: {
          args: Prisma.AIChatHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AIChatHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.AIChatHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AIChatHistoryPayload>
        }
        aggregate: {
          args: Prisma.AIChatHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAIChatHistory>
        }
        groupBy: {
          args: Prisma.AIChatHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AIChatHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.AIChatHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AIChatHistoryCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName',
  level: 'level'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const MajorAccessScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  majorId: 'majorId'
} as const

export type MajorAccessScalarFieldEnum = (typeof MajorAccessScalarFieldEnum)[keyof typeof MajorAccessScalarFieldEnum]


export const MajorsScalarFieldEnum = {
  id: 'id',
  majorName: 'majorName',
  accreditation: 'accreditation'
} as const

export type MajorsScalarFieldEnum = (typeof MajorsScalarFieldEnum)[keyof typeof MajorsScalarFieldEnum]


export const CriteriaScalarFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaScalarFieldEnum = (typeof CriteriaScalarFieldEnum)[keyof typeof CriteriaScalarFieldEnum]


export const FileLinkScalarFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  fileId: 'fileId',
  criteriaLink: 'criteriaLink',
  page: 'page'
} as const

export type FileLinkScalarFieldEnum = (typeof FileLinkScalarFieldEnum)[keyof typeof FileLinkScalarFieldEnum]


export const FilesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType',
  createdAt: 'createdAt',
  updateAt: 'updateAt',
  status: 'status'
} as const

export type FilesScalarFieldEnum = (typeof FilesScalarFieldEnum)[keyof typeof FilesScalarFieldEnum]


export const ActivityLogsScalarFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId',
  action: 'action',
  createdAt: 'createdAt'
} as const

export type ActivityLogsScalarFieldEnum = (typeof ActivityLogsScalarFieldEnum)[keyof typeof ActivityLogsScalarFieldEnum]


export const AIChatHistoryScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content'
} as const

export type AIChatHistoryScalarFieldEnum = (typeof AIChatHistoryScalarFieldEnum)[keyof typeof AIChatHistoryScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UsersOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName'
} as const

export type UsersOrderByRelevanceFieldEnum = (typeof UsersOrderByRelevanceFieldEnum)[keyof typeof UsersOrderByRelevanceFieldEnum]


export const MajorAccessOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  majorId: 'majorId'
} as const

export type MajorAccessOrderByRelevanceFieldEnum = (typeof MajorAccessOrderByRelevanceFieldEnum)[keyof typeof MajorAccessOrderByRelevanceFieldEnum]


export const MajorsOrderByRelevanceFieldEnum = {
  id: 'id',
  majorName: 'majorName'
} as const

export type MajorsOrderByRelevanceFieldEnum = (typeof MajorsOrderByRelevanceFieldEnum)[keyof typeof MajorsOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const CriteriaOrderByRelevanceFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaOrderByRelevanceFieldEnum = (typeof CriteriaOrderByRelevanceFieldEnum)[keyof typeof CriteriaOrderByRelevanceFieldEnum]


export const FileLinkOrderByRelevanceFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  fileId: 'fileId',
  criteriaLink: 'criteriaLink'
} as const

export type FileLinkOrderByRelevanceFieldEnum = (typeof FileLinkOrderByRelevanceFieldEnum)[keyof typeof FileLinkOrderByRelevanceFieldEnum]


export const FilesOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType'
} as const

export type FilesOrderByRelevanceFieldEnum = (typeof FilesOrderByRelevanceFieldEnum)[keyof typeof FilesOrderByRelevanceFieldEnum]


export const ActivityLogsOrderByRelevanceFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId'
} as const

export type ActivityLogsOrderByRelevanceFieldEnum = (typeof ActivityLogsOrderByRelevanceFieldEnum)[keyof typeof ActivityLogsOrderByRelevanceFieldEnum]


export const AIChatHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content'
} as const

export type AIChatHistoryOrderByRelevanceFieldEnum = (typeof AIChatHistoryOrderByRelevanceFieldEnum)[keyof typeof AIChatHistoryOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Level'
 */
export type EnumLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Level'>
    


/**
 * Reference to a field of type 'Accreditation'
 */
export type EnumAccreditationFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Accreditation'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Status'
 */
export type EnumStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Status'>
    


/**
 * Reference to a field of type 'Action'
 */
export type EnumActionFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Action'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  users?: Prisma.UsersOmit
  majorAccess?: Prisma.MajorAccessOmit
  majors?: Prisma.MajorsOmit
  criteria?: Prisma.CriteriaOmit
  fileLink?: Prisma.FileLinkOmit
  files?: Prisma.FilesOmit
  activityLogs?: Prisma.ActivityLogsOmit
  aIChatHistory?: Prisma.AIChatHistoryOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

