
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Users: 'Users',
  MajorAccess: 'MajorAccess',
  Majors: 'Majors',
  Criteria: 'Criteria',
  FileLink: 'FileLink',
  Files: 'Files',
  ActivityLogs: 'ActivityLogs',
  AISession: 'AISession',
  AIChatHistory: 'AIChatHistory',
  AIModel: 'AIModel',
  AIConfig: 'AIConfig'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName',
  level: 'level'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const MajorAccessScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  majorId: 'majorId'
} as const

export type MajorAccessScalarFieldEnum = (typeof MajorAccessScalarFieldEnum)[keyof typeof MajorAccessScalarFieldEnum]


export const MajorsScalarFieldEnum = {
  id: 'id',
  majorName: 'majorName',
  accreditation: 'accreditation'
} as const

export type MajorsScalarFieldEnum = (typeof MajorsScalarFieldEnum)[keyof typeof MajorsScalarFieldEnum]


export const CriteriaScalarFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaScalarFieldEnum = (typeof CriteriaScalarFieldEnum)[keyof typeof CriteriaScalarFieldEnum]


export const FileLinkScalarFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  fileId: 'fileId',
  criteriaLink: 'criteriaLink',
  page: 'page'
} as const

export type FileLinkScalarFieldEnum = (typeof FileLinkScalarFieldEnum)[keyof typeof FileLinkScalarFieldEnum]


export const FilesScalarFieldEnum = {
  id: 'id',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType',
  createdAt: 'createdAt',
  updateAt: 'updateAt',
  status: 'status'
} as const

export type FilesScalarFieldEnum = (typeof FilesScalarFieldEnum)[keyof typeof FilesScalarFieldEnum]


export const ActivityLogsScalarFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId',
  action: 'action',
  createdAt: 'createdAt'
} as const

export type ActivityLogsScalarFieldEnum = (typeof ActivityLogsScalarFieldEnum)[keyof typeof ActivityLogsScalarFieldEnum]


export const AISessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  topic: 'topic',
  createdAt: 'createdAt'
} as const

export type AISessionScalarFieldEnum = (typeof AISessionScalarFieldEnum)[keyof typeof AISessionScalarFieldEnum]


export const AIChatHistoryScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content',
  createdAt: 'createdAt'
} as const

export type AIChatHistoryScalarFieldEnum = (typeof AIChatHistoryScalarFieldEnum)[keyof typeof AIChatHistoryScalarFieldEnum]


export const AIModelScalarFieldEnum = {
  id: 'id',
  provider: 'provider',
  modelName: 'modelName'
} as const

export type AIModelScalarFieldEnum = (typeof AIModelScalarFieldEnum)[keyof typeof AIModelScalarFieldEnum]


export const AIConfigScalarFieldEnum = {
  key: 'key',
  value: 'value'
} as const

export type AIConfigScalarFieldEnum = (typeof AIConfigScalarFieldEnum)[keyof typeof AIConfigScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UsersOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName'
} as const

export type UsersOrderByRelevanceFieldEnum = (typeof UsersOrderByRelevanceFieldEnum)[keyof typeof UsersOrderByRelevanceFieldEnum]


export const MajorAccessOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  majorId: 'majorId'
} as const

export type MajorAccessOrderByRelevanceFieldEnum = (typeof MajorAccessOrderByRelevanceFieldEnum)[keyof typeof MajorAccessOrderByRelevanceFieldEnum]


export const MajorsOrderByRelevanceFieldEnum = {
  id: 'id',
  majorName: 'majorName'
} as const

export type MajorsOrderByRelevanceFieldEnum = (typeof MajorsOrderByRelevanceFieldEnum)[keyof typeof MajorsOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const CriteriaOrderByRelevanceFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaOrderByRelevanceFieldEnum = (typeof CriteriaOrderByRelevanceFieldEnum)[keyof typeof CriteriaOrderByRelevanceFieldEnum]


export const FileLinkOrderByRelevanceFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  fileId: 'fileId',
  criteriaLink: 'criteriaLink'
} as const

export type FileLinkOrderByRelevanceFieldEnum = (typeof FileLinkOrderByRelevanceFieldEnum)[keyof typeof FileLinkOrderByRelevanceFieldEnum]


export const FilesOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType'
} as const

export type FilesOrderByRelevanceFieldEnum = (typeof FilesOrderByRelevanceFieldEnum)[keyof typeof FilesOrderByRelevanceFieldEnum]


export const ActivityLogsOrderByRelevanceFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId'
} as const

export type ActivityLogsOrderByRelevanceFieldEnum = (typeof ActivityLogsOrderByRelevanceFieldEnum)[keyof typeof ActivityLogsOrderByRelevanceFieldEnum]


export const AISessionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  topic: 'topic'
} as const

export type AISessionOrderByRelevanceFieldEnum = (typeof AISessionOrderByRelevanceFieldEnum)[keyof typeof AISessionOrderByRelevanceFieldEnum]


export const AIChatHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  role: 'role',
  content: 'content'
} as const

export type AIChatHistoryOrderByRelevanceFieldEnum = (typeof AIChatHistoryOrderByRelevanceFieldEnum)[keyof typeof AIChatHistoryOrderByRelevanceFieldEnum]


export const AIModelOrderByRelevanceFieldEnum = {
  id: 'id',
  modelName: 'modelName'
} as const

export type AIModelOrderByRelevanceFieldEnum = (typeof AIModelOrderByRelevanceFieldEnum)[keyof typeof AIModelOrderByRelevanceFieldEnum]


export const AIConfigOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
} as const

export type AIConfigOrderByRelevanceFieldEnum = (typeof AIConfigOrderByRelevanceFieldEnum)[keyof typeof AIConfigOrderByRelevanceFieldEnum]

