
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Users: 'Users',
  Majors: 'Majors',
  Criteria: 'Criteria',
  Files: 'Files',
  ActivityLogs: 'ActivityLogs'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName',
  majorId: 'majorId',
  level: 'level'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const MajorsScalarFieldEnum = {
  id: 'id',
  majorName: 'majorName'
} as const

export type MajorsScalarFieldEnum = (typeof MajorsScalarFieldEnum)[keyof typeof MajorsScalarFieldEnum]


export const CriteriaScalarFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaScalarFieldEnum = (typeof CriteriaScalarFieldEnum)[keyof typeof CriteriaScalarFieldEnum]


export const FilesScalarFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType',
  createdAt: 'createdAt',
  updateAt: 'updateAt'
} as const

export type FilesScalarFieldEnum = (typeof FilesScalarFieldEnum)[keyof typeof FilesScalarFieldEnum]


export const ActivityLogsScalarFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId',
  action: 'action',
  createdAt: 'createdAt'
} as const

export type ActivityLogsScalarFieldEnum = (typeof ActivityLogsScalarFieldEnum)[keyof typeof ActivityLogsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UsersOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  fullName: 'fullName',
  majorId: 'majorId'
} as const

export type UsersOrderByRelevanceFieldEnum = (typeof UsersOrderByRelevanceFieldEnum)[keyof typeof UsersOrderByRelevanceFieldEnum]


export const MajorsOrderByRelevanceFieldEnum = {
  id: 'id',
  majorName: 'majorName'
} as const

export type MajorsOrderByRelevanceFieldEnum = (typeof MajorsOrderByRelevanceFieldEnum)[keyof typeof MajorsOrderByRelevanceFieldEnum]


export const CriteriaOrderByRelevanceFieldEnum = {
  id: 'id',
  parent: 'parent',
  code: 'code',
  name: 'name',
  description: 'description',
  access: 'access'
} as const

export type CriteriaOrderByRelevanceFieldEnum = (typeof CriteriaOrderByRelevanceFieldEnum)[keyof typeof CriteriaOrderByRelevanceFieldEnum]


export const FilesOrderByRelevanceFieldEnum = {
  id: 'id',
  criteriaId: 'criteriaId',
  title: 'title',
  fileName: 'fileName',
  fileHash: 'fileHash',
  mimeType: 'mimeType'
} as const

export type FilesOrderByRelevanceFieldEnum = (typeof FilesOrderByRelevanceFieldEnum)[keyof typeof FilesOrderByRelevanceFieldEnum]


export const ActivityLogsOrderByRelevanceFieldEnum = {
  id: 'id',
  fileId: 'fileId',
  userId: 'userId'
} as const

export type ActivityLogsOrderByRelevanceFieldEnum = (typeof ActivityLogsOrderByRelevanceFieldEnum)[keyof typeof ActivityLogsOrderByRelevanceFieldEnum]

