
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ActivityLogs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ActivityLogs
 * 
 */
export type ActivityLogsModel = runtime.Types.Result.DefaultSelection<Prisma.$ActivityLogsPayload>

export type AggregateActivityLogs = {
  _count: ActivityLogsCountAggregateOutputType | null
  _min: ActivityLogsMinAggregateOutputType | null
  _max: ActivityLogsMaxAggregateOutputType | null
}

export type ActivityLogsMinAggregateOutputType = {
  id: string | null
  fileId: string | null
  userId: string | null
  action: $Enums.Action | null
  createdAt: Date | null
}

export type ActivityLogsMaxAggregateOutputType = {
  id: string | null
  fileId: string | null
  userId: string | null
  action: $Enums.Action | null
  createdAt: Date | null
}

export type ActivityLogsCountAggregateOutputType = {
  id: number
  fileId: number
  userId: number
  action: number
  createdAt: number
  _all: number
}


export type ActivityLogsMinAggregateInputType = {
  id?: true
  fileId?: true
  userId?: true
  action?: true
  createdAt?: true
}

export type ActivityLogsMaxAggregateInputType = {
  id?: true
  fileId?: true
  userId?: true
  action?: true
  createdAt?: true
}

export type ActivityLogsCountAggregateInputType = {
  id?: true
  fileId?: true
  userId?: true
  action?: true
  createdAt?: true
  _all?: true
}

export type ActivityLogsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActivityLogs to aggregate.
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActivityLogs to fetch.
   */
  orderBy?: Prisma.ActivityLogsOrderByWithRelationInput | Prisma.ActivityLogsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActivityLogsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActivityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActivityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ActivityLogs
  **/
  _count?: true | ActivityLogsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActivityLogsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActivityLogsMaxAggregateInputType
}

export type GetActivityLogsAggregateType<T extends ActivityLogsAggregateArgs> = {
      [P in keyof T & keyof AggregateActivityLogs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActivityLogs[P]>
    : Prisma.GetScalarType<T[P], AggregateActivityLogs[P]>
}




export type ActivityLogsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityLogsWhereInput
  orderBy?: Prisma.ActivityLogsOrderByWithAggregationInput | Prisma.ActivityLogsOrderByWithAggregationInput[]
  by: Prisma.ActivityLogsScalarFieldEnum[] | Prisma.ActivityLogsScalarFieldEnum
  having?: Prisma.ActivityLogsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActivityLogsCountAggregateInputType | true
  _min?: ActivityLogsMinAggregateInputType
  _max?: ActivityLogsMaxAggregateInputType
}

export type ActivityLogsGroupByOutputType = {
  id: string
  fileId: string
  userId: string
  action: $Enums.Action
  createdAt: Date
  _count: ActivityLogsCountAggregateOutputType | null
  _min: ActivityLogsMinAggregateOutputType | null
  _max: ActivityLogsMaxAggregateOutputType | null
}

export type GetActivityLogsGroupByPayload<T extends ActivityLogsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActivityLogsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActivityLogsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActivityLogsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActivityLogsGroupByOutputType[P]>
      }
    >
  >



export type ActivityLogsWhereInput = {
  AND?: Prisma.ActivityLogsWhereInput | Prisma.ActivityLogsWhereInput[]
  OR?: Prisma.ActivityLogsWhereInput[]
  NOT?: Prisma.ActivityLogsWhereInput | Prisma.ActivityLogsWhereInput[]
  id?: Prisma.StringFilter<"ActivityLogs"> | string
  fileId?: Prisma.StringFilter<"ActivityLogs"> | string
  userId?: Prisma.StringFilter<"ActivityLogs"> | string
  action?: Prisma.EnumActionFilter<"ActivityLogs"> | $Enums.Action
  createdAt?: Prisma.DateTimeFilter<"ActivityLogs"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  files?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
}

export type ActivityLogsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  users?: Prisma.UsersOrderByWithRelationInput
  files?: Prisma.FilesOrderByWithRelationInput
  _relevance?: Prisma.ActivityLogsOrderByRelevanceInput
}

export type ActivityLogsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ActivityLogsWhereInput | Prisma.ActivityLogsWhereInput[]
  OR?: Prisma.ActivityLogsWhereInput[]
  NOT?: Prisma.ActivityLogsWhereInput | Prisma.ActivityLogsWhereInput[]
  fileId?: Prisma.StringFilter<"ActivityLogs"> | string
  userId?: Prisma.StringFilter<"ActivityLogs"> | string
  action?: Prisma.EnumActionFilter<"ActivityLogs"> | $Enums.Action
  createdAt?: Prisma.DateTimeFilter<"ActivityLogs"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  files?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
}, "id">

export type ActivityLogsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ActivityLogsCountOrderByAggregateInput
  _max?: Prisma.ActivityLogsMaxOrderByAggregateInput
  _min?: Prisma.ActivityLogsMinOrderByAggregateInput
}

export type ActivityLogsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActivityLogsScalarWhereWithAggregatesInput | Prisma.ActivityLogsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActivityLogsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActivityLogsScalarWhereWithAggregatesInput | Prisma.ActivityLogsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ActivityLogs"> | string
  fileId?: Prisma.StringWithAggregatesFilter<"ActivityLogs"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ActivityLogs"> | string
  action?: Prisma.EnumActionWithAggregatesFilter<"ActivityLogs"> | $Enums.Action
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ActivityLogs"> | Date | string
}

export type ActivityLogsCreateInput = {
  id?: string
  action: $Enums.Action
  createdAt?: Date | string
  users: Prisma.UsersCreateNestedOneWithoutActivityLogsInput
  files: Prisma.FilesCreateNestedOneWithoutActivityLogsInput
}

export type ActivityLogsUncheckedCreateInput = {
  id?: string
  fileId: string
  userId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UsersUpdateOneRequiredWithoutActivityLogsNestedInput
  files?: Prisma.FilesUpdateOneRequiredWithoutActivityLogsNestedInput
}

export type ActivityLogsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsCreateManyInput = {
  id?: string
  fileId: string
  userId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsListRelationFilter = {
  every?: Prisma.ActivityLogsWhereInput
  some?: Prisma.ActivityLogsWhereInput
  none?: Prisma.ActivityLogsWhereInput
}

export type ActivityLogsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ActivityLogsOrderByRelevanceInput = {
  fields: Prisma.ActivityLogsOrderByRelevanceFieldEnum | Prisma.ActivityLogsOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ActivityLogsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityLogsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityLogsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ActivityLogsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput> | Prisma.ActivityLogsCreateWithoutUsersInput[] | Prisma.ActivityLogsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutUsersInput | Prisma.ActivityLogsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.ActivityLogsCreateManyUsersInputEnvelope
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
}

export type ActivityLogsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput> | Prisma.ActivityLogsCreateWithoutUsersInput[] | Prisma.ActivityLogsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutUsersInput | Prisma.ActivityLogsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.ActivityLogsCreateManyUsersInputEnvelope
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
}

export type ActivityLogsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput> | Prisma.ActivityLogsCreateWithoutUsersInput[] | Prisma.ActivityLogsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutUsersInput | Prisma.ActivityLogsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ActivityLogsUpsertWithWhereUniqueWithoutUsersInput | Prisma.ActivityLogsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.ActivityLogsCreateManyUsersInputEnvelope
  set?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  disconnect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  delete?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  update?: Prisma.ActivityLogsUpdateWithWhereUniqueWithoutUsersInput | Prisma.ActivityLogsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ActivityLogsUpdateManyWithWhereWithoutUsersInput | Prisma.ActivityLogsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
}

export type ActivityLogsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput> | Prisma.ActivityLogsCreateWithoutUsersInput[] | Prisma.ActivityLogsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutUsersInput | Prisma.ActivityLogsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ActivityLogsUpsertWithWhereUniqueWithoutUsersInput | Prisma.ActivityLogsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.ActivityLogsCreateManyUsersInputEnvelope
  set?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  disconnect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  delete?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  update?: Prisma.ActivityLogsUpdateWithWhereUniqueWithoutUsersInput | Prisma.ActivityLogsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ActivityLogsUpdateManyWithWhereWithoutUsersInput | Prisma.ActivityLogsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
}

export type ActivityLogsCreateNestedManyWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput> | Prisma.ActivityLogsCreateWithoutFilesInput[] | Prisma.ActivityLogsUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutFilesInput | Prisma.ActivityLogsCreateOrConnectWithoutFilesInput[]
  createMany?: Prisma.ActivityLogsCreateManyFilesInputEnvelope
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
}

export type ActivityLogsUncheckedCreateNestedManyWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput> | Prisma.ActivityLogsCreateWithoutFilesInput[] | Prisma.ActivityLogsUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutFilesInput | Prisma.ActivityLogsCreateOrConnectWithoutFilesInput[]
  createMany?: Prisma.ActivityLogsCreateManyFilesInputEnvelope
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
}

export type ActivityLogsUpdateManyWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput> | Prisma.ActivityLogsCreateWithoutFilesInput[] | Prisma.ActivityLogsUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutFilesInput | Prisma.ActivityLogsCreateOrConnectWithoutFilesInput[]
  upsert?: Prisma.ActivityLogsUpsertWithWhereUniqueWithoutFilesInput | Prisma.ActivityLogsUpsertWithWhereUniqueWithoutFilesInput[]
  createMany?: Prisma.ActivityLogsCreateManyFilesInputEnvelope
  set?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  disconnect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  delete?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  update?: Prisma.ActivityLogsUpdateWithWhereUniqueWithoutFilesInput | Prisma.ActivityLogsUpdateWithWhereUniqueWithoutFilesInput[]
  updateMany?: Prisma.ActivityLogsUpdateManyWithWhereWithoutFilesInput | Prisma.ActivityLogsUpdateManyWithWhereWithoutFilesInput[]
  deleteMany?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
}

export type ActivityLogsUncheckedUpdateManyWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput> | Prisma.ActivityLogsCreateWithoutFilesInput[] | Prisma.ActivityLogsUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.ActivityLogsCreateOrConnectWithoutFilesInput | Prisma.ActivityLogsCreateOrConnectWithoutFilesInput[]
  upsert?: Prisma.ActivityLogsUpsertWithWhereUniqueWithoutFilesInput | Prisma.ActivityLogsUpsertWithWhereUniqueWithoutFilesInput[]
  createMany?: Prisma.ActivityLogsCreateManyFilesInputEnvelope
  set?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  disconnect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  delete?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  connect?: Prisma.ActivityLogsWhereUniqueInput | Prisma.ActivityLogsWhereUniqueInput[]
  update?: Prisma.ActivityLogsUpdateWithWhereUniqueWithoutFilesInput | Prisma.ActivityLogsUpdateWithWhereUniqueWithoutFilesInput[]
  updateMany?: Prisma.ActivityLogsUpdateManyWithWhereWithoutFilesInput | Prisma.ActivityLogsUpdateManyWithWhereWithoutFilesInput[]
  deleteMany?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
}

export type EnumActionFieldUpdateOperationsInput = {
  set?: $Enums.Action
}

export type ActivityLogsCreateWithoutUsersInput = {
  id?: string
  action: $Enums.Action
  createdAt?: Date | string
  files: Prisma.FilesCreateNestedOneWithoutActivityLogsInput
}

export type ActivityLogsUncheckedCreateWithoutUsersInput = {
  id?: string
  fileId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsCreateOrConnectWithoutUsersInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  create: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput>
}

export type ActivityLogsCreateManyUsersInputEnvelope = {
  data: Prisma.ActivityLogsCreateManyUsersInput | Prisma.ActivityLogsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type ActivityLogsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  update: Prisma.XOR<Prisma.ActivityLogsUpdateWithoutUsersInput, Prisma.ActivityLogsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.ActivityLogsCreateWithoutUsersInput, Prisma.ActivityLogsUncheckedCreateWithoutUsersInput>
}

export type ActivityLogsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  data: Prisma.XOR<Prisma.ActivityLogsUpdateWithoutUsersInput, Prisma.ActivityLogsUncheckedUpdateWithoutUsersInput>
}

export type ActivityLogsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.ActivityLogsScalarWhereInput
  data: Prisma.XOR<Prisma.ActivityLogsUpdateManyMutationInput, Prisma.ActivityLogsUncheckedUpdateManyWithoutUsersInput>
}

export type ActivityLogsScalarWhereInput = {
  AND?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
  OR?: Prisma.ActivityLogsScalarWhereInput[]
  NOT?: Prisma.ActivityLogsScalarWhereInput | Prisma.ActivityLogsScalarWhereInput[]
  id?: Prisma.StringFilter<"ActivityLogs"> | string
  fileId?: Prisma.StringFilter<"ActivityLogs"> | string
  userId?: Prisma.StringFilter<"ActivityLogs"> | string
  action?: Prisma.EnumActionFilter<"ActivityLogs"> | $Enums.Action
  createdAt?: Prisma.DateTimeFilter<"ActivityLogs"> | Date | string
}

export type ActivityLogsCreateWithoutFilesInput = {
  id?: string
  action: $Enums.Action
  createdAt?: Date | string
  users: Prisma.UsersCreateNestedOneWithoutActivityLogsInput
}

export type ActivityLogsUncheckedCreateWithoutFilesInput = {
  id?: string
  userId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsCreateOrConnectWithoutFilesInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  create: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput>
}

export type ActivityLogsCreateManyFilesInputEnvelope = {
  data: Prisma.ActivityLogsCreateManyFilesInput | Prisma.ActivityLogsCreateManyFilesInput[]
  skipDuplicates?: boolean
}

export type ActivityLogsUpsertWithWhereUniqueWithoutFilesInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  update: Prisma.XOR<Prisma.ActivityLogsUpdateWithoutFilesInput, Prisma.ActivityLogsUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.ActivityLogsCreateWithoutFilesInput, Prisma.ActivityLogsUncheckedCreateWithoutFilesInput>
}

export type ActivityLogsUpdateWithWhereUniqueWithoutFilesInput = {
  where: Prisma.ActivityLogsWhereUniqueInput
  data: Prisma.XOR<Prisma.ActivityLogsUpdateWithoutFilesInput, Prisma.ActivityLogsUncheckedUpdateWithoutFilesInput>
}

export type ActivityLogsUpdateManyWithWhereWithoutFilesInput = {
  where: Prisma.ActivityLogsScalarWhereInput
  data: Prisma.XOR<Prisma.ActivityLogsUpdateManyMutationInput, Prisma.ActivityLogsUncheckedUpdateManyWithoutFilesInput>
}

export type ActivityLogsCreateManyUsersInput = {
  id?: string
  fileId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.FilesUpdateOneRequiredWithoutActivityLogsNestedInput
}

export type ActivityLogsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsCreateManyFilesInput = {
  id?: string
  userId: string
  action: $Enums.Action
  createdAt?: Date | string
}

export type ActivityLogsUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.UsersUpdateOneRequiredWithoutActivityLogsNestedInput
}

export type ActivityLogsUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ActivityLogsUncheckedUpdateManyWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumActionFieldUpdateOperationsInput | $Enums.Action
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ActivityLogsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  userId?: boolean
  action?: boolean
  createdAt?: boolean
  users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  files?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["activityLogs"]>



export type ActivityLogsSelectScalar = {
  id?: boolean
  fileId?: boolean
  userId?: boolean
  action?: boolean
  createdAt?: boolean
}

export type ActivityLogsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileId" | "userId" | "action" | "createdAt", ExtArgs["result"]["activityLogs"]>
export type ActivityLogsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  files?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}

export type $ActivityLogsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ActivityLogs"
  objects: {
    users: Prisma.$UsersPayload<ExtArgs>
    files: Prisma.$FilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileId: string
    userId: string
    action: $Enums.Action
    createdAt: Date
  }, ExtArgs["result"]["activityLogs"]>
  composites: {}
}

export type ActivityLogsGetPayload<S extends boolean | null | undefined | ActivityLogsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload, S>

export type ActivityLogsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActivityLogsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActivityLogsCountAggregateInputType | true
  }

export interface ActivityLogsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ActivityLogs'], meta: { name: 'ActivityLogs' } }
  /**
   * Find zero or one ActivityLogs that matches the filter.
   * @param {ActivityLogsFindUniqueArgs} args - Arguments to find a ActivityLogs
   * @example
   * // Get one ActivityLogs
   * const activityLogs = await prisma.activityLogs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActivityLogsFindUniqueArgs>(args: Prisma.SelectSubset<T, ActivityLogsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ActivityLogs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActivityLogsFindUniqueOrThrowArgs} args - Arguments to find a ActivityLogs
   * @example
   * // Get one ActivityLogs
   * const activityLogs = await prisma.activityLogs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActivityLogsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActivityLogsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActivityLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsFindFirstArgs} args - Arguments to find a ActivityLogs
   * @example
   * // Get one ActivityLogs
   * const activityLogs = await prisma.activityLogs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActivityLogsFindFirstArgs>(args?: Prisma.SelectSubset<T, ActivityLogsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ActivityLogs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsFindFirstOrThrowArgs} args - Arguments to find a ActivityLogs
   * @example
   * // Get one ActivityLogs
   * const activityLogs = await prisma.activityLogs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActivityLogsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActivityLogsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ActivityLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ActivityLogs
   * const activityLogs = await prisma.activityLogs.findMany()
   * 
   * // Get first 10 ActivityLogs
   * const activityLogs = await prisma.activityLogs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const activityLogsWithIdOnly = await prisma.activityLogs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ActivityLogsFindManyArgs>(args?: Prisma.SelectSubset<T, ActivityLogsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ActivityLogs.
   * @param {ActivityLogsCreateArgs} args - Arguments to create a ActivityLogs.
   * @example
   * // Create one ActivityLogs
   * const ActivityLogs = await prisma.activityLogs.create({
   *   data: {
   *     // ... data to create a ActivityLogs
   *   }
   * })
   * 
   */
  create<T extends ActivityLogsCreateArgs>(args: Prisma.SelectSubset<T, ActivityLogsCreateArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ActivityLogs.
   * @param {ActivityLogsCreateManyArgs} args - Arguments to create many ActivityLogs.
   * @example
   * // Create many ActivityLogs
   * const activityLogs = await prisma.activityLogs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActivityLogsCreateManyArgs>(args?: Prisma.SelectSubset<T, ActivityLogsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ActivityLogs.
   * @param {ActivityLogsDeleteArgs} args - Arguments to delete one ActivityLogs.
   * @example
   * // Delete one ActivityLogs
   * const ActivityLogs = await prisma.activityLogs.delete({
   *   where: {
   *     // ... filter to delete one ActivityLogs
   *   }
   * })
   * 
   */
  delete<T extends ActivityLogsDeleteArgs>(args: Prisma.SelectSubset<T, ActivityLogsDeleteArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ActivityLogs.
   * @param {ActivityLogsUpdateArgs} args - Arguments to update one ActivityLogs.
   * @example
   * // Update one ActivityLogs
   * const activityLogs = await prisma.activityLogs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActivityLogsUpdateArgs>(args: Prisma.SelectSubset<T, ActivityLogsUpdateArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ActivityLogs.
   * @param {ActivityLogsDeleteManyArgs} args - Arguments to filter ActivityLogs to delete.
   * @example
   * // Delete a few ActivityLogs
   * const { count } = await prisma.activityLogs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActivityLogsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActivityLogsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ActivityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ActivityLogs
   * const activityLogs = await prisma.activityLogs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActivityLogsUpdateManyArgs>(args: Prisma.SelectSubset<T, ActivityLogsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ActivityLogs.
   * @param {ActivityLogsUpsertArgs} args - Arguments to update or create a ActivityLogs.
   * @example
   * // Update or create a ActivityLogs
   * const activityLogs = await prisma.activityLogs.upsert({
   *   create: {
   *     // ... data to create a ActivityLogs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ActivityLogs we want to update
   *   }
   * })
   */
  upsert<T extends ActivityLogsUpsertArgs>(args: Prisma.SelectSubset<T, ActivityLogsUpsertArgs<ExtArgs>>): Prisma.Prisma__ActivityLogsClient<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ActivityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsCountArgs} args - Arguments to filter ActivityLogs to count.
   * @example
   * // Count the number of ActivityLogs
   * const count = await prisma.activityLogs.count({
   *   where: {
   *     // ... the filter for the ActivityLogs we want to count
   *   }
   * })
  **/
  count<T extends ActivityLogsCountArgs>(
    args?: Prisma.Subset<T, ActivityLogsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActivityLogsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ActivityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActivityLogsAggregateArgs>(args: Prisma.Subset<T, ActivityLogsAggregateArgs>): Prisma.PrismaPromise<GetActivityLogsAggregateType<T>>

  /**
   * Group by ActivityLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActivityLogsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActivityLogsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActivityLogsGroupByArgs['orderBy'] }
      : { orderBy?: ActivityLogsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActivityLogsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActivityLogsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ActivityLogs model
 */
readonly fields: ActivityLogsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ActivityLogs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActivityLogsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  files<T extends Prisma.FilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilesDefaultArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ActivityLogs model
 */
export interface ActivityLogsFieldRefs {
  readonly id: Prisma.FieldRef<"ActivityLogs", 'String'>
  readonly fileId: Prisma.FieldRef<"ActivityLogs", 'String'>
  readonly userId: Prisma.FieldRef<"ActivityLogs", 'String'>
  readonly action: Prisma.FieldRef<"ActivityLogs", 'Action'>
  readonly createdAt: Prisma.FieldRef<"ActivityLogs", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ActivityLogs findUnique
 */
export type ActivityLogsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter, which ActivityLogs to fetch.
   */
  where: Prisma.ActivityLogsWhereUniqueInput
}

/**
 * ActivityLogs findUniqueOrThrow
 */
export type ActivityLogsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter, which ActivityLogs to fetch.
   */
  where: Prisma.ActivityLogsWhereUniqueInput
}

/**
 * ActivityLogs findFirst
 */
export type ActivityLogsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter, which ActivityLogs to fetch.
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActivityLogs to fetch.
   */
  orderBy?: Prisma.ActivityLogsOrderByWithRelationInput | Prisma.ActivityLogsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActivityLogs.
   */
  cursor?: Prisma.ActivityLogsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActivityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActivityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActivityLogs.
   */
  distinct?: Prisma.ActivityLogsScalarFieldEnum | Prisma.ActivityLogsScalarFieldEnum[]
}

/**
 * ActivityLogs findFirstOrThrow
 */
export type ActivityLogsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter, which ActivityLogs to fetch.
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActivityLogs to fetch.
   */
  orderBy?: Prisma.ActivityLogsOrderByWithRelationInput | Prisma.ActivityLogsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ActivityLogs.
   */
  cursor?: Prisma.ActivityLogsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActivityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActivityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActivityLogs.
   */
  distinct?: Prisma.ActivityLogsScalarFieldEnum | Prisma.ActivityLogsScalarFieldEnum[]
}

/**
 * ActivityLogs findMany
 */
export type ActivityLogsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter, which ActivityLogs to fetch.
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ActivityLogs to fetch.
   */
  orderBy?: Prisma.ActivityLogsOrderByWithRelationInput | Prisma.ActivityLogsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ActivityLogs.
   */
  cursor?: Prisma.ActivityLogsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ActivityLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ActivityLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ActivityLogs.
   */
  distinct?: Prisma.ActivityLogsScalarFieldEnum | Prisma.ActivityLogsScalarFieldEnum[]
}

/**
 * ActivityLogs create
 */
export type ActivityLogsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * The data needed to create a ActivityLogs.
   */
  data: Prisma.XOR<Prisma.ActivityLogsCreateInput, Prisma.ActivityLogsUncheckedCreateInput>
}

/**
 * ActivityLogs createMany
 */
export type ActivityLogsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ActivityLogs.
   */
  data: Prisma.ActivityLogsCreateManyInput | Prisma.ActivityLogsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ActivityLogs update
 */
export type ActivityLogsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * The data needed to update a ActivityLogs.
   */
  data: Prisma.XOR<Prisma.ActivityLogsUpdateInput, Prisma.ActivityLogsUncheckedUpdateInput>
  /**
   * Choose, which ActivityLogs to update.
   */
  where: Prisma.ActivityLogsWhereUniqueInput
}

/**
 * ActivityLogs updateMany
 */
export type ActivityLogsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ActivityLogs.
   */
  data: Prisma.XOR<Prisma.ActivityLogsUpdateManyMutationInput, Prisma.ActivityLogsUncheckedUpdateManyInput>
  /**
   * Filter which ActivityLogs to update
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * Limit how many ActivityLogs to update.
   */
  limit?: number
}

/**
 * ActivityLogs upsert
 */
export type ActivityLogsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * The filter to search for the ActivityLogs to update in case it exists.
   */
  where: Prisma.ActivityLogsWhereUniqueInput
  /**
   * In case the ActivityLogs found by the `where` argument doesn't exist, create a new ActivityLogs with this data.
   */
  create: Prisma.XOR<Prisma.ActivityLogsCreateInput, Prisma.ActivityLogsUncheckedCreateInput>
  /**
   * In case the ActivityLogs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActivityLogsUpdateInput, Prisma.ActivityLogsUncheckedUpdateInput>
}

/**
 * ActivityLogs delete
 */
export type ActivityLogsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  /**
   * Filter which ActivityLogs to delete.
   */
  where: Prisma.ActivityLogsWhereUniqueInput
}

/**
 * ActivityLogs deleteMany
 */
export type ActivityLogsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ActivityLogs to delete
   */
  where?: Prisma.ActivityLogsWhereInput
  /**
   * Limit how many ActivityLogs to delete.
   */
  limit?: number
}

/**
 * ActivityLogs without action
 */
export type ActivityLogsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
}
