
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AISession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AISession
 * 
 */
export type AISessionModel = runtime.Types.Result.DefaultSelection<Prisma.$AISessionPayload>

export type AggregateAISession = {
  _count: AISessionCountAggregateOutputType | null
  _min: AISessionMinAggregateOutputType | null
  _max: AISessionMaxAggregateOutputType | null
}

export type AISessionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  topic: string | null
  createdAt: Date | null
}

export type AISessionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  topic: string | null
  createdAt: Date | null
}

export type AISessionCountAggregateOutputType = {
  id: number
  userId: number
  topic: number
  createdAt: number
  _all: number
}


export type AISessionMinAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  createdAt?: true
}

export type AISessionMaxAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  createdAt?: true
}

export type AISessionCountAggregateInputType = {
  id?: true
  userId?: true
  topic?: true
  createdAt?: true
  _all?: true
}

export type AISessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AISession to aggregate.
   */
  where?: Prisma.AISessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AISessions to fetch.
   */
  orderBy?: Prisma.AISessionOrderByWithRelationInput | Prisma.AISessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AISessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AISessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AISessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AISessions
  **/
  _count?: true | AISessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AISessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AISessionMaxAggregateInputType
}

export type GetAISessionAggregateType<T extends AISessionAggregateArgs> = {
      [P in keyof T & keyof AggregateAISession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAISession[P]>
    : Prisma.GetScalarType<T[P], AggregateAISession[P]>
}




export type AISessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AISessionWhereInput
  orderBy?: Prisma.AISessionOrderByWithAggregationInput | Prisma.AISessionOrderByWithAggregationInput[]
  by: Prisma.AISessionScalarFieldEnum[] | Prisma.AISessionScalarFieldEnum
  having?: Prisma.AISessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AISessionCountAggregateInputType | true
  _min?: AISessionMinAggregateInputType
  _max?: AISessionMaxAggregateInputType
}

export type AISessionGroupByOutputType = {
  id: string
  userId: string
  topic: string
  createdAt: Date
  _count: AISessionCountAggregateOutputType | null
  _min: AISessionMinAggregateOutputType | null
  _max: AISessionMaxAggregateOutputType | null
}

export type GetAISessionGroupByPayload<T extends AISessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AISessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AISessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AISessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AISessionGroupByOutputType[P]>
      }
    >
  >



export type AISessionWhereInput = {
  AND?: Prisma.AISessionWhereInput | Prisma.AISessionWhereInput[]
  OR?: Prisma.AISessionWhereInput[]
  NOT?: Prisma.AISessionWhereInput | Prisma.AISessionWhereInput[]
  id?: Prisma.StringFilter<"AISession"> | string
  userId?: Prisma.StringFilter<"AISession"> | string
  topic?: Prisma.StringFilter<"AISession"> | string
  createdAt?: Prisma.DateTimeFilter<"AISession"> | Date | string
  Users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  aichatHistories?: Prisma.AIChatHistoryListRelationFilter
}

export type AISessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  Users?: Prisma.UsersOrderByWithRelationInput
  aichatHistories?: Prisma.AIChatHistoryOrderByRelationAggregateInput
  _relevance?: Prisma.AISessionOrderByRelevanceInput
}

export type AISessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AISessionWhereInput | Prisma.AISessionWhereInput[]
  OR?: Prisma.AISessionWhereInput[]
  NOT?: Prisma.AISessionWhereInput | Prisma.AISessionWhereInput[]
  userId?: Prisma.StringFilter<"AISession"> | string
  topic?: Prisma.StringFilter<"AISession"> | string
  createdAt?: Prisma.DateTimeFilter<"AISession"> | Date | string
  Users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  aichatHistories?: Prisma.AIChatHistoryListRelationFilter
}, "id">

export type AISessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AISessionCountOrderByAggregateInput
  _max?: Prisma.AISessionMaxOrderByAggregateInput
  _min?: Prisma.AISessionMinOrderByAggregateInput
}

export type AISessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.AISessionScalarWhereWithAggregatesInput | Prisma.AISessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.AISessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AISessionScalarWhereWithAggregatesInput | Prisma.AISessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AISession"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AISession"> | string
  topic?: Prisma.StringWithAggregatesFilter<"AISession"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AISession"> | Date | string
}

export type AISessionCreateInput = {
  id?: string
  topic: string
  createdAt?: Date | string
  Users: Prisma.UsersCreateNestedOneWithoutAisessionsInput
  aichatHistories?: Prisma.AIChatHistoryCreateNestedManyWithoutAISessionInput
}

export type AISessionUncheckedCreateInput = {
  id?: string
  userId: string
  topic: string
  createdAt?: Date | string
  aichatHistories?: Prisma.AIChatHistoryUncheckedCreateNestedManyWithoutAISessionInput
}

export type AISessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Users?: Prisma.UsersUpdateOneRequiredWithoutAisessionsNestedInput
  aichatHistories?: Prisma.AIChatHistoryUpdateManyWithoutAISessionNestedInput
}

export type AISessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aichatHistories?: Prisma.AIChatHistoryUncheckedUpdateManyWithoutAISessionNestedInput
}

export type AISessionCreateManyInput = {
  id?: string
  userId: string
  topic: string
  createdAt?: Date | string
}

export type AISessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AISessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AISessionListRelationFilter = {
  every?: Prisma.AISessionWhereInput
  some?: Prisma.AISessionWhereInput
  none?: Prisma.AISessionWhereInput
}

export type AISessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AISessionOrderByRelevanceInput = {
  fields: Prisma.AISessionOrderByRelevanceFieldEnum | Prisma.AISessionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AISessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AISessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AISessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AISessionScalarRelationFilter = {
  is?: Prisma.AISessionWhereInput
  isNot?: Prisma.AISessionWhereInput
}

export type AISessionCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput> | Prisma.AISessionCreateWithoutUsersInput[] | Prisma.AISessionUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutUsersInput | Prisma.AISessionCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.AISessionCreateManyUsersInputEnvelope
  connect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
}

export type AISessionUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput> | Prisma.AISessionCreateWithoutUsersInput[] | Prisma.AISessionUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutUsersInput | Prisma.AISessionCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.AISessionCreateManyUsersInputEnvelope
  connect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
}

export type AISessionUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput> | Prisma.AISessionCreateWithoutUsersInput[] | Prisma.AISessionUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutUsersInput | Prisma.AISessionCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.AISessionUpsertWithWhereUniqueWithoutUsersInput | Prisma.AISessionUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.AISessionCreateManyUsersInputEnvelope
  set?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  disconnect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  delete?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  connect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  update?: Prisma.AISessionUpdateWithWhereUniqueWithoutUsersInput | Prisma.AISessionUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.AISessionUpdateManyWithWhereWithoutUsersInput | Prisma.AISessionUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.AISessionScalarWhereInput | Prisma.AISessionScalarWhereInput[]
}

export type AISessionUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput> | Prisma.AISessionCreateWithoutUsersInput[] | Prisma.AISessionUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutUsersInput | Prisma.AISessionCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.AISessionUpsertWithWhereUniqueWithoutUsersInput | Prisma.AISessionUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.AISessionCreateManyUsersInputEnvelope
  set?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  disconnect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  delete?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  connect?: Prisma.AISessionWhereUniqueInput | Prisma.AISessionWhereUniqueInput[]
  update?: Prisma.AISessionUpdateWithWhereUniqueWithoutUsersInput | Prisma.AISessionUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.AISessionUpdateManyWithWhereWithoutUsersInput | Prisma.AISessionUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.AISessionScalarWhereInput | Prisma.AISessionScalarWhereInput[]
}

export type AISessionCreateNestedOneWithoutAichatHistoriesInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedCreateWithoutAichatHistoriesInput>
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutAichatHistoriesInput
  connect?: Prisma.AISessionWhereUniqueInput
}

export type AISessionUpdateOneRequiredWithoutAichatHistoriesNestedInput = {
  create?: Prisma.XOR<Prisma.AISessionCreateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedCreateWithoutAichatHistoriesInput>
  connectOrCreate?: Prisma.AISessionCreateOrConnectWithoutAichatHistoriesInput
  upsert?: Prisma.AISessionUpsertWithoutAichatHistoriesInput
  connect?: Prisma.AISessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AISessionUpdateToOneWithWhereWithoutAichatHistoriesInput, Prisma.AISessionUpdateWithoutAichatHistoriesInput>, Prisma.AISessionUncheckedUpdateWithoutAichatHistoriesInput>
}

export type AISessionCreateWithoutUsersInput = {
  id?: string
  topic: string
  createdAt?: Date | string
  aichatHistories?: Prisma.AIChatHistoryCreateNestedManyWithoutAISessionInput
}

export type AISessionUncheckedCreateWithoutUsersInput = {
  id?: string
  topic: string
  createdAt?: Date | string
  aichatHistories?: Prisma.AIChatHistoryUncheckedCreateNestedManyWithoutAISessionInput
}

export type AISessionCreateOrConnectWithoutUsersInput = {
  where: Prisma.AISessionWhereUniqueInput
  create: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput>
}

export type AISessionCreateManyUsersInputEnvelope = {
  data: Prisma.AISessionCreateManyUsersInput | Prisma.AISessionCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type AISessionUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.AISessionWhereUniqueInput
  update: Prisma.XOR<Prisma.AISessionUpdateWithoutUsersInput, Prisma.AISessionUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.AISessionCreateWithoutUsersInput, Prisma.AISessionUncheckedCreateWithoutUsersInput>
}

export type AISessionUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.AISessionWhereUniqueInput
  data: Prisma.XOR<Prisma.AISessionUpdateWithoutUsersInput, Prisma.AISessionUncheckedUpdateWithoutUsersInput>
}

export type AISessionUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.AISessionScalarWhereInput
  data: Prisma.XOR<Prisma.AISessionUpdateManyMutationInput, Prisma.AISessionUncheckedUpdateManyWithoutUsersInput>
}

export type AISessionScalarWhereInput = {
  AND?: Prisma.AISessionScalarWhereInput | Prisma.AISessionScalarWhereInput[]
  OR?: Prisma.AISessionScalarWhereInput[]
  NOT?: Prisma.AISessionScalarWhereInput | Prisma.AISessionScalarWhereInput[]
  id?: Prisma.StringFilter<"AISession"> | string
  userId?: Prisma.StringFilter<"AISession"> | string
  topic?: Prisma.StringFilter<"AISession"> | string
  createdAt?: Prisma.DateTimeFilter<"AISession"> | Date | string
}

export type AISessionCreateWithoutAichatHistoriesInput = {
  id?: string
  topic: string
  createdAt?: Date | string
  Users: Prisma.UsersCreateNestedOneWithoutAisessionsInput
}

export type AISessionUncheckedCreateWithoutAichatHistoriesInput = {
  id?: string
  userId: string
  topic: string
  createdAt?: Date | string
}

export type AISessionCreateOrConnectWithoutAichatHistoriesInput = {
  where: Prisma.AISessionWhereUniqueInput
  create: Prisma.XOR<Prisma.AISessionCreateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedCreateWithoutAichatHistoriesInput>
}

export type AISessionUpsertWithoutAichatHistoriesInput = {
  update: Prisma.XOR<Prisma.AISessionUpdateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedUpdateWithoutAichatHistoriesInput>
  create: Prisma.XOR<Prisma.AISessionCreateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedCreateWithoutAichatHistoriesInput>
  where?: Prisma.AISessionWhereInput
}

export type AISessionUpdateToOneWithWhereWithoutAichatHistoriesInput = {
  where?: Prisma.AISessionWhereInput
  data: Prisma.XOR<Prisma.AISessionUpdateWithoutAichatHistoriesInput, Prisma.AISessionUncheckedUpdateWithoutAichatHistoriesInput>
}

export type AISessionUpdateWithoutAichatHistoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Users?: Prisma.UsersUpdateOneRequiredWithoutAisessionsNestedInput
}

export type AISessionUncheckedUpdateWithoutAichatHistoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AISessionCreateManyUsersInput = {
  id?: string
  topic: string
  createdAt?: Date | string
}

export type AISessionUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aichatHistories?: Prisma.AIChatHistoryUpdateManyWithoutAISessionNestedInput
}

export type AISessionUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aichatHistories?: Prisma.AIChatHistoryUncheckedUpdateManyWithoutAISessionNestedInput
}

export type AISessionUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AISessionCountOutputType
 */

export type AISessionCountOutputType = {
  aichatHistories: number
}

export type AISessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  aichatHistories?: boolean | AISessionCountOutputTypeCountAichatHistoriesArgs
}

/**
 * AISessionCountOutputType without action
 */
export type AISessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISessionCountOutputType
   */
  select?: Prisma.AISessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AISessionCountOutputType without action
 */
export type AISessionCountOutputTypeCountAichatHistoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AIChatHistoryWhereInput
}


export type AISessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  topic?: boolean
  createdAt?: boolean
  Users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  aichatHistories?: boolean | Prisma.AISession$aichatHistoriesArgs<ExtArgs>
  _count?: boolean | Prisma.AISessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aISession"]>



export type AISessionSelectScalar = {
  id?: boolean
  userId?: boolean
  topic?: boolean
  createdAt?: boolean
}

export type AISessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "topic" | "createdAt", ExtArgs["result"]["aISession"]>
export type AISessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  aichatHistories?: boolean | Prisma.AISession$aichatHistoriesArgs<ExtArgs>
  _count?: boolean | Prisma.AISessionCountOutputTypeDefaultArgs<ExtArgs>
}

export type $AISessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AISession"
  objects: {
    Users: Prisma.$UsersPayload<ExtArgs>
    aichatHistories: Prisma.$AIChatHistoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    topic: string
    createdAt: Date
  }, ExtArgs["result"]["aISession"]>
  composites: {}
}

export type AISessionGetPayload<S extends boolean | null | undefined | AISessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AISessionPayload, S>

export type AISessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AISessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AISessionCountAggregateInputType | true
  }

export interface AISessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AISession'], meta: { name: 'AISession' } }
  /**
   * Find zero or one AISession that matches the filter.
   * @param {AISessionFindUniqueArgs} args - Arguments to find a AISession
   * @example
   * // Get one AISession
   * const aISession = await prisma.aISession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AISessionFindUniqueArgs>(args: Prisma.SelectSubset<T, AISessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AISession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AISessionFindUniqueOrThrowArgs} args - Arguments to find a AISession
   * @example
   * // Get one AISession
   * const aISession = await prisma.aISession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AISessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AISessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AISession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionFindFirstArgs} args - Arguments to find a AISession
   * @example
   * // Get one AISession
   * const aISession = await prisma.aISession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AISessionFindFirstArgs>(args?: Prisma.SelectSubset<T, AISessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AISession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionFindFirstOrThrowArgs} args - Arguments to find a AISession
   * @example
   * // Get one AISession
   * const aISession = await prisma.aISession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AISessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AISessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AISessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AISessions
   * const aISessions = await prisma.aISession.findMany()
   * 
   * // Get first 10 AISessions
   * const aISessions = await prisma.aISession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const aISessionWithIdOnly = await prisma.aISession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AISessionFindManyArgs>(args?: Prisma.SelectSubset<T, AISessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AISession.
   * @param {AISessionCreateArgs} args - Arguments to create a AISession.
   * @example
   * // Create one AISession
   * const AISession = await prisma.aISession.create({
   *   data: {
   *     // ... data to create a AISession
   *   }
   * })
   * 
   */
  create<T extends AISessionCreateArgs>(args: Prisma.SelectSubset<T, AISessionCreateArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AISessions.
   * @param {AISessionCreateManyArgs} args - Arguments to create many AISessions.
   * @example
   * // Create many AISessions
   * const aISession = await prisma.aISession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AISessionCreateManyArgs>(args?: Prisma.SelectSubset<T, AISessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a AISession.
   * @param {AISessionDeleteArgs} args - Arguments to delete one AISession.
   * @example
   * // Delete one AISession
   * const AISession = await prisma.aISession.delete({
   *   where: {
   *     // ... filter to delete one AISession
   *   }
   * })
   * 
   */
  delete<T extends AISessionDeleteArgs>(args: Prisma.SelectSubset<T, AISessionDeleteArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AISession.
   * @param {AISessionUpdateArgs} args - Arguments to update one AISession.
   * @example
   * // Update one AISession
   * const aISession = await prisma.aISession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AISessionUpdateArgs>(args: Prisma.SelectSubset<T, AISessionUpdateArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AISessions.
   * @param {AISessionDeleteManyArgs} args - Arguments to filter AISessions to delete.
   * @example
   * // Delete a few AISessions
   * const { count } = await prisma.aISession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AISessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, AISessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AISessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AISessions
   * const aISession = await prisma.aISession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AISessionUpdateManyArgs>(args: Prisma.SelectSubset<T, AISessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one AISession.
   * @param {AISessionUpsertArgs} args - Arguments to update or create a AISession.
   * @example
   * // Update or create a AISession
   * const aISession = await prisma.aISession.upsert({
   *   create: {
   *     // ... data to create a AISession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AISession we want to update
   *   }
   * })
   */
  upsert<T extends AISessionUpsertArgs>(args: Prisma.SelectSubset<T, AISessionUpsertArgs<ExtArgs>>): Prisma.Prisma__AISessionClient<runtime.Types.Result.GetResult<Prisma.$AISessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AISessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionCountArgs} args - Arguments to filter AISessions to count.
   * @example
   * // Count the number of AISessions
   * const count = await prisma.aISession.count({
   *   where: {
   *     // ... the filter for the AISessions we want to count
   *   }
   * })
  **/
  count<T extends AISessionCountArgs>(
    args?: Prisma.Subset<T, AISessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AISessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AISession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AISessionAggregateArgs>(args: Prisma.Subset<T, AISessionAggregateArgs>): Prisma.PrismaPromise<GetAISessionAggregateType<T>>

  /**
   * Group by AISession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AISessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AISessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AISessionGroupByArgs['orderBy'] }
      : { orderBy?: AISessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AISessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAISessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AISession model
 */
readonly fields: AISessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AISession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AISessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Users<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  aichatHistories<T extends Prisma.AISession$aichatHistoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AISession$aichatHistoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AIChatHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AISession model
 */
export interface AISessionFieldRefs {
  readonly id: Prisma.FieldRef<"AISession", 'String'>
  readonly userId: Prisma.FieldRef<"AISession", 'String'>
  readonly topic: Prisma.FieldRef<"AISession", 'String'>
  readonly createdAt: Prisma.FieldRef<"AISession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AISession findUnique
 */
export type AISessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter, which AISession to fetch.
   */
  where: Prisma.AISessionWhereUniqueInput
}

/**
 * AISession findUniqueOrThrow
 */
export type AISessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter, which AISession to fetch.
   */
  where: Prisma.AISessionWhereUniqueInput
}

/**
 * AISession findFirst
 */
export type AISessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter, which AISession to fetch.
   */
  where?: Prisma.AISessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AISessions to fetch.
   */
  orderBy?: Prisma.AISessionOrderByWithRelationInput | Prisma.AISessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AISessions.
   */
  cursor?: Prisma.AISessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AISessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AISessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AISessions.
   */
  distinct?: Prisma.AISessionScalarFieldEnum | Prisma.AISessionScalarFieldEnum[]
}

/**
 * AISession findFirstOrThrow
 */
export type AISessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter, which AISession to fetch.
   */
  where?: Prisma.AISessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AISessions to fetch.
   */
  orderBy?: Prisma.AISessionOrderByWithRelationInput | Prisma.AISessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AISessions.
   */
  cursor?: Prisma.AISessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AISessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AISessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AISessions.
   */
  distinct?: Prisma.AISessionScalarFieldEnum | Prisma.AISessionScalarFieldEnum[]
}

/**
 * AISession findMany
 */
export type AISessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter, which AISessions to fetch.
   */
  where?: Prisma.AISessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AISessions to fetch.
   */
  orderBy?: Prisma.AISessionOrderByWithRelationInput | Prisma.AISessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AISessions.
   */
  cursor?: Prisma.AISessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AISessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AISessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AISessions.
   */
  distinct?: Prisma.AISessionScalarFieldEnum | Prisma.AISessionScalarFieldEnum[]
}

/**
 * AISession create
 */
export type AISessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * The data needed to create a AISession.
   */
  data: Prisma.XOR<Prisma.AISessionCreateInput, Prisma.AISessionUncheckedCreateInput>
}

/**
 * AISession createMany
 */
export type AISessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AISessions.
   */
  data: Prisma.AISessionCreateManyInput | Prisma.AISessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AISession update
 */
export type AISessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * The data needed to update a AISession.
   */
  data: Prisma.XOR<Prisma.AISessionUpdateInput, Prisma.AISessionUncheckedUpdateInput>
  /**
   * Choose, which AISession to update.
   */
  where: Prisma.AISessionWhereUniqueInput
}

/**
 * AISession updateMany
 */
export type AISessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AISessions.
   */
  data: Prisma.XOR<Prisma.AISessionUpdateManyMutationInput, Prisma.AISessionUncheckedUpdateManyInput>
  /**
   * Filter which AISessions to update
   */
  where?: Prisma.AISessionWhereInput
  /**
   * Limit how many AISessions to update.
   */
  limit?: number
}

/**
 * AISession upsert
 */
export type AISessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * The filter to search for the AISession to update in case it exists.
   */
  where: Prisma.AISessionWhereUniqueInput
  /**
   * In case the AISession found by the `where` argument doesn't exist, create a new AISession with this data.
   */
  create: Prisma.XOR<Prisma.AISessionCreateInput, Prisma.AISessionUncheckedCreateInput>
  /**
   * In case the AISession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AISessionUpdateInput, Prisma.AISessionUncheckedUpdateInput>
}

/**
 * AISession delete
 */
export type AISessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
  /**
   * Filter which AISession to delete.
   */
  where: Prisma.AISessionWhereUniqueInput
}

/**
 * AISession deleteMany
 */
export type AISessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AISessions to delete
   */
  where?: Prisma.AISessionWhereInput
  /**
   * Limit how many AISessions to delete.
   */
  limit?: number
}

/**
 * AISession.aichatHistories
 */
export type AISession$aichatHistoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AIChatHistory
   */
  select?: Prisma.AIChatHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AIChatHistory
   */
  omit?: Prisma.AIChatHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AIChatHistoryInclude<ExtArgs> | null
  where?: Prisma.AIChatHistoryWhereInput
  orderBy?: Prisma.AIChatHistoryOrderByWithRelationInput | Prisma.AIChatHistoryOrderByWithRelationInput[]
  cursor?: Prisma.AIChatHistoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AIChatHistoryScalarFieldEnum | Prisma.AIChatHistoryScalarFieldEnum[]
}

/**
 * AISession without action
 */
export type AISessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AISession
   */
  select?: Prisma.AISessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AISession
   */
  omit?: Prisma.AISessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AISessionInclude<ExtArgs> | null
}
