
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Files` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Files
 * 
 */
export type FilesModel = runtime.Types.Result.DefaultSelection<Prisma.$FilesPayload>

export type AggregateFiles = {
  _count: FilesCountAggregateOutputType | null
  _min: FilesMinAggregateOutputType | null
  _max: FilesMaxAggregateOutputType | null
}

export type FilesMinAggregateOutputType = {
  id: string | null
  title: string | null
  fileName: string | null
  fileHash: string | null
  mimeType: string | null
  createdAt: Date | null
  updateAt: Date | null
  status: $Enums.Status | null
}

export type FilesMaxAggregateOutputType = {
  id: string | null
  title: string | null
  fileName: string | null
  fileHash: string | null
  mimeType: string | null
  createdAt: Date | null
  updateAt: Date | null
  status: $Enums.Status | null
}

export type FilesCountAggregateOutputType = {
  id: number
  title: number
  fileName: number
  fileHash: number
  mimeType: number
  createdAt: number
  updateAt: number
  status: number
  _all: number
}


export type FilesMinAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  fileHash?: true
  mimeType?: true
  createdAt?: true
  updateAt?: true
  status?: true
}

export type FilesMaxAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  fileHash?: true
  mimeType?: true
  createdAt?: true
  updateAt?: true
  status?: true
}

export type FilesCountAggregateInputType = {
  id?: true
  title?: true
  fileName?: true
  fileHash?: true
  mimeType?: true
  createdAt?: true
  updateAt?: true
  status?: true
  _all?: true
}

export type FilesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Files to aggregate.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Files
  **/
  _count?: true | FilesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilesMaxAggregateInputType
}

export type GetFilesAggregateType<T extends FilesAggregateArgs> = {
      [P in keyof T & keyof AggregateFiles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFiles[P]>
    : Prisma.GetScalarType<T[P], AggregateFiles[P]>
}




export type FilesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilesWhereInput
  orderBy?: Prisma.FilesOrderByWithAggregationInput | Prisma.FilesOrderByWithAggregationInput[]
  by: Prisma.FilesScalarFieldEnum[] | Prisma.FilesScalarFieldEnum
  having?: Prisma.FilesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilesCountAggregateInputType | true
  _min?: FilesMinAggregateInputType
  _max?: FilesMaxAggregateInputType
}

export type FilesGroupByOutputType = {
  id: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt: Date
  updateAt: Date
  status: $Enums.Status
  _count: FilesCountAggregateOutputType | null
  _min: FilesMinAggregateOutputType | null
  _max: FilesMaxAggregateOutputType | null
}

export type GetFilesGroupByPayload<T extends FilesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilesGroupByOutputType[P]>
      }
    >
  >



export type FilesWhereInput = {
  AND?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  OR?: Prisma.FilesWhereInput[]
  NOT?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  id?: Prisma.StringFilter<"Files"> | string
  title?: Prisma.StringFilter<"Files"> | string
  fileName?: Prisma.StringFilter<"Files"> | string
  fileHash?: Prisma.StringFilter<"Files"> | string
  mimeType?: Prisma.StringFilter<"Files"> | string
  createdAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  updateAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  status?: Prisma.EnumStatusFilter<"Files"> | $Enums.Status
  activityLogs?: Prisma.ActivityLogsListRelationFilter
  fileLinks?: Prisma.FileLinkListRelationFilter
}

export type FilesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileHash?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  activityLogs?: Prisma.ActivityLogsOrderByRelationAggregateInput
  fileLinks?: Prisma.FileLinkOrderByRelationAggregateInput
  _relevance?: Prisma.FilesOrderByRelevanceInput
}

export type FilesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  OR?: Prisma.FilesWhereInput[]
  NOT?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  title?: Prisma.StringFilter<"Files"> | string
  fileName?: Prisma.StringFilter<"Files"> | string
  fileHash?: Prisma.StringFilter<"Files"> | string
  mimeType?: Prisma.StringFilter<"Files"> | string
  createdAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  updateAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  status?: Prisma.EnumStatusFilter<"Files"> | $Enums.Status
  activityLogs?: Prisma.ActivityLogsListRelationFilter
  fileLinks?: Prisma.FileLinkListRelationFilter
}, "id">

export type FilesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileHash?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.FilesCountOrderByAggregateInput
  _max?: Prisma.FilesMaxOrderByAggregateInput
  _min?: Prisma.FilesMinOrderByAggregateInput
}

export type FilesScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilesScalarWhereWithAggregatesInput | Prisma.FilesScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilesScalarWhereWithAggregatesInput | Prisma.FilesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Files"> | string
  title?: Prisma.StringWithAggregatesFilter<"Files"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"Files"> | string
  fileHash?: Prisma.StringWithAggregatesFilter<"Files"> | string
  mimeType?: Prisma.StringWithAggregatesFilter<"Files"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Files"> | Date | string
  updateAt?: Prisma.DateTimeWithAggregatesFilter<"Files"> | Date | string
  status?: Prisma.EnumStatusWithAggregatesFilter<"Files"> | $Enums.Status
}

export type FilesCreateInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  activityLogs?: Prisma.ActivityLogsCreateNestedManyWithoutFilesInput
  fileLinks?: Prisma.FileLinkCreateNestedManyWithoutFilesInput
}

export type FilesUncheckedCreateInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  activityLogs?: Prisma.ActivityLogsUncheckedCreateNestedManyWithoutFilesInput
  fileLinks?: Prisma.FileLinkUncheckedCreateNestedManyWithoutFilesInput
}

export type FilesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  activityLogs?: Prisma.ActivityLogsUpdateManyWithoutFilesNestedInput
  fileLinks?: Prisma.FileLinkUpdateManyWithoutFilesNestedInput
}

export type FilesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  activityLogs?: Prisma.ActivityLogsUncheckedUpdateManyWithoutFilesNestedInput
  fileLinks?: Prisma.FileLinkUncheckedUpdateManyWithoutFilesNestedInput
}

export type FilesCreateManyInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
}

export type FilesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type FilesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
}

export type FilesScalarRelationFilter = {
  is?: Prisma.FilesWhereInput
  isNot?: Prisma.FilesWhereInput
}

export type FilesOrderByRelevanceInput = {
  fields: Prisma.FilesOrderByRelevanceFieldEnum | Prisma.FilesOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FilesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileHash?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type FilesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileHash?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type FilesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileHash?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type FilesCreateNestedOneWithoutFileLinksInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFileLinksInput, Prisma.FilesUncheckedCreateWithoutFileLinksInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFileLinksInput
  connect?: Prisma.FilesWhereUniqueInput
}

export type FilesUpdateOneRequiredWithoutFileLinksNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFileLinksInput, Prisma.FilesUncheckedCreateWithoutFileLinksInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFileLinksInput
  upsert?: Prisma.FilesUpsertWithoutFileLinksInput
  connect?: Prisma.FilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilesUpdateToOneWithWhereWithoutFileLinksInput, Prisma.FilesUpdateWithoutFileLinksInput>, Prisma.FilesUncheckedUpdateWithoutFileLinksInput>
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EnumStatusFieldUpdateOperationsInput = {
  set?: $Enums.Status
}

export type FilesCreateNestedOneWithoutActivityLogsInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutActivityLogsInput, Prisma.FilesUncheckedCreateWithoutActivityLogsInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutActivityLogsInput
  connect?: Prisma.FilesWhereUniqueInput
}

export type FilesUpdateOneRequiredWithoutActivityLogsNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutActivityLogsInput, Prisma.FilesUncheckedCreateWithoutActivityLogsInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutActivityLogsInput
  upsert?: Prisma.FilesUpsertWithoutActivityLogsInput
  connect?: Prisma.FilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilesUpdateToOneWithWhereWithoutActivityLogsInput, Prisma.FilesUpdateWithoutActivityLogsInput>, Prisma.FilesUncheckedUpdateWithoutActivityLogsInput>
}

export type FilesCreateWithoutFileLinksInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  activityLogs?: Prisma.ActivityLogsCreateNestedManyWithoutFilesInput
}

export type FilesUncheckedCreateWithoutFileLinksInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  activityLogs?: Prisma.ActivityLogsUncheckedCreateNestedManyWithoutFilesInput
}

export type FilesCreateOrConnectWithoutFileLinksInput = {
  where: Prisma.FilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesCreateWithoutFileLinksInput, Prisma.FilesUncheckedCreateWithoutFileLinksInput>
}

export type FilesUpsertWithoutFileLinksInput = {
  update: Prisma.XOR<Prisma.FilesUpdateWithoutFileLinksInput, Prisma.FilesUncheckedUpdateWithoutFileLinksInput>
  create: Prisma.XOR<Prisma.FilesCreateWithoutFileLinksInput, Prisma.FilesUncheckedCreateWithoutFileLinksInput>
  where?: Prisma.FilesWhereInput
}

export type FilesUpdateToOneWithWhereWithoutFileLinksInput = {
  where?: Prisma.FilesWhereInput
  data: Prisma.XOR<Prisma.FilesUpdateWithoutFileLinksInput, Prisma.FilesUncheckedUpdateWithoutFileLinksInput>
}

export type FilesUpdateWithoutFileLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  activityLogs?: Prisma.ActivityLogsUpdateManyWithoutFilesNestedInput
}

export type FilesUncheckedUpdateWithoutFileLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  activityLogs?: Prisma.ActivityLogsUncheckedUpdateManyWithoutFilesNestedInput
}

export type FilesCreateWithoutActivityLogsInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  fileLinks?: Prisma.FileLinkCreateNestedManyWithoutFilesInput
}

export type FilesUncheckedCreateWithoutActivityLogsInput = {
  id?: string
  title: string
  fileName: string
  fileHash: string
  mimeType: string
  createdAt?: Date | string
  updateAt?: Date | string
  status: $Enums.Status
  fileLinks?: Prisma.FileLinkUncheckedCreateNestedManyWithoutFilesInput
}

export type FilesCreateOrConnectWithoutActivityLogsInput = {
  where: Prisma.FilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesCreateWithoutActivityLogsInput, Prisma.FilesUncheckedCreateWithoutActivityLogsInput>
}

export type FilesUpsertWithoutActivityLogsInput = {
  update: Prisma.XOR<Prisma.FilesUpdateWithoutActivityLogsInput, Prisma.FilesUncheckedUpdateWithoutActivityLogsInput>
  create: Prisma.XOR<Prisma.FilesCreateWithoutActivityLogsInput, Prisma.FilesUncheckedCreateWithoutActivityLogsInput>
  where?: Prisma.FilesWhereInput
}

export type FilesUpdateToOneWithWhereWithoutActivityLogsInput = {
  where?: Prisma.FilesWhereInput
  data: Prisma.XOR<Prisma.FilesUpdateWithoutActivityLogsInput, Prisma.FilesUncheckedUpdateWithoutActivityLogsInput>
}

export type FilesUpdateWithoutActivityLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  fileLinks?: Prisma.FileLinkUpdateManyWithoutFilesNestedInput
}

export type FilesUncheckedUpdateWithoutActivityLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileHash?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  fileLinks?: Prisma.FileLinkUncheckedUpdateManyWithoutFilesNestedInput
}


/**
 * Count Type FilesCountOutputType
 */

export type FilesCountOutputType = {
  activityLogs: number
  fileLinks: number
}

export type FilesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  activityLogs?: boolean | FilesCountOutputTypeCountActivityLogsArgs
  fileLinks?: boolean | FilesCountOutputTypeCountFileLinksArgs
}

/**
 * FilesCountOutputType without action
 */
export type FilesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesCountOutputType
   */
  select?: Prisma.FilesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FilesCountOutputType without action
 */
export type FilesCountOutputTypeCountActivityLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActivityLogsWhereInput
}

/**
 * FilesCountOutputType without action
 */
export type FilesCountOutputTypeCountFileLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileLinkWhereInput
}


export type FilesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  fileName?: boolean
  fileHash?: boolean
  mimeType?: boolean
  createdAt?: boolean
  updateAt?: boolean
  status?: boolean
  activityLogs?: boolean | Prisma.Files$activityLogsArgs<ExtArgs>
  fileLinks?: boolean | Prisma.Files$fileLinksArgs<ExtArgs>
  _count?: boolean | Prisma.FilesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["files"]>



export type FilesSelectScalar = {
  id?: boolean
  title?: boolean
  fileName?: boolean
  fileHash?: boolean
  mimeType?: boolean
  createdAt?: boolean
  updateAt?: boolean
  status?: boolean
}

export type FilesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "fileName" | "fileHash" | "mimeType" | "createdAt" | "updateAt" | "status", ExtArgs["result"]["files"]>
export type FilesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  activityLogs?: boolean | Prisma.Files$activityLogsArgs<ExtArgs>
  fileLinks?: boolean | Prisma.Files$fileLinksArgs<ExtArgs>
  _count?: boolean | Prisma.FilesCountOutputTypeDefaultArgs<ExtArgs>
}

export type $FilesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Files"
  objects: {
    activityLogs: Prisma.$ActivityLogsPayload<ExtArgs>[]
    fileLinks: Prisma.$FileLinkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    fileName: string
    fileHash: string
    mimeType: string
    createdAt: Date
    updateAt: Date
    status: $Enums.Status
  }, ExtArgs["result"]["files"]>
  composites: {}
}

export type FilesGetPayload<S extends boolean | null | undefined | FilesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilesPayload, S>

export type FilesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilesCountAggregateInputType | true
  }

export interface FilesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Files'], meta: { name: 'Files' } }
  /**
   * Find zero or one Files that matches the filter.
   * @param {FilesFindUniqueArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilesFindUniqueArgs>(args: Prisma.SelectSubset<T, FilesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Files that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilesFindUniqueOrThrowArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindFirstArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilesFindFirstArgs>(args?: Prisma.SelectSubset<T, FilesFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Files that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindFirstOrThrowArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Files
   * const files = await prisma.files.findMany()
   * 
   * // Get first 10 Files
   * const files = await prisma.files.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filesWithIdOnly = await prisma.files.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilesFindManyArgs>(args?: Prisma.SelectSubset<T, FilesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Files.
   * @param {FilesCreateArgs} args - Arguments to create a Files.
   * @example
   * // Create one Files
   * const Files = await prisma.files.create({
   *   data: {
   *     // ... data to create a Files
   *   }
   * })
   * 
   */
  create<T extends FilesCreateArgs>(args: Prisma.SelectSubset<T, FilesCreateArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Files.
   * @param {FilesCreateManyArgs} args - Arguments to create many Files.
   * @example
   * // Create many Files
   * const files = await prisma.files.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilesCreateManyArgs>(args?: Prisma.SelectSubset<T, FilesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Files.
   * @param {FilesDeleteArgs} args - Arguments to delete one Files.
   * @example
   * // Delete one Files
   * const Files = await prisma.files.delete({
   *   where: {
   *     // ... filter to delete one Files
   *   }
   * })
   * 
   */
  delete<T extends FilesDeleteArgs>(args: Prisma.SelectSubset<T, FilesDeleteArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Files.
   * @param {FilesUpdateArgs} args - Arguments to update one Files.
   * @example
   * // Update one Files
   * const files = await prisma.files.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilesUpdateArgs>(args: Prisma.SelectSubset<T, FilesUpdateArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Files.
   * @param {FilesDeleteManyArgs} args - Arguments to filter Files to delete.
   * @example
   * // Delete a few Files
   * const { count } = await prisma.files.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilesDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Files
   * const files = await prisma.files.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilesUpdateManyArgs>(args: Prisma.SelectSubset<T, FilesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Files.
   * @param {FilesUpsertArgs} args - Arguments to update or create a Files.
   * @example
   * // Update or create a Files
   * const files = await prisma.files.upsert({
   *   create: {
   *     // ... data to create a Files
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Files we want to update
   *   }
   * })
   */
  upsert<T extends FilesUpsertArgs>(args: Prisma.SelectSubset<T, FilesUpsertArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesCountArgs} args - Arguments to filter Files to count.
   * @example
   * // Count the number of Files
   * const count = await prisma.files.count({
   *   where: {
   *     // ... the filter for the Files we want to count
   *   }
   * })
  **/
  count<T extends FilesCountArgs>(
    args?: Prisma.Subset<T, FilesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilesAggregateArgs>(args: Prisma.Subset<T, FilesAggregateArgs>): Prisma.PrismaPromise<GetFilesAggregateType<T>>

  /**
   * Group by Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilesGroupByArgs['orderBy'] }
      : { orderBy?: FilesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Files model
 */
readonly fields: FilesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Files.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  activityLogs<T extends Prisma.Files$activityLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Files$activityLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActivityLogsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  fileLinks<T extends Prisma.Files$fileLinksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Files$fileLinksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Files model
 */
export interface FilesFieldRefs {
  readonly id: Prisma.FieldRef<"Files", 'String'>
  readonly title: Prisma.FieldRef<"Files", 'String'>
  readonly fileName: Prisma.FieldRef<"Files", 'String'>
  readonly fileHash: Prisma.FieldRef<"Files", 'String'>
  readonly mimeType: Prisma.FieldRef<"Files", 'String'>
  readonly createdAt: Prisma.FieldRef<"Files", 'DateTime'>
  readonly updateAt: Prisma.FieldRef<"Files", 'DateTime'>
  readonly status: Prisma.FieldRef<"Files", 'Status'>
}
    

// Custom InputTypes
/**
 * Files findUnique
 */
export type FilesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files findUniqueOrThrow
 */
export type FilesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files findFirst
 */
export type FilesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files findFirstOrThrow
 */
export type FilesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files findMany
 */
export type FilesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files create
 */
export type FilesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The data needed to create a Files.
   */
  data: Prisma.XOR<Prisma.FilesCreateInput, Prisma.FilesUncheckedCreateInput>
}

/**
 * Files createMany
 */
export type FilesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Files.
   */
  data: Prisma.FilesCreateManyInput | Prisma.FilesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Files update
 */
export type FilesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The data needed to update a Files.
   */
  data: Prisma.XOR<Prisma.FilesUpdateInput, Prisma.FilesUncheckedUpdateInput>
  /**
   * Choose, which Files to update.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files updateMany
 */
export type FilesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Files.
   */
  data: Prisma.XOR<Prisma.FilesUpdateManyMutationInput, Prisma.FilesUncheckedUpdateManyInput>
  /**
   * Filter which Files to update
   */
  where?: Prisma.FilesWhereInput
  /**
   * Limit how many Files to update.
   */
  limit?: number
}

/**
 * Files upsert
 */
export type FilesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The filter to search for the Files to update in case it exists.
   */
  where: Prisma.FilesWhereUniqueInput
  /**
   * In case the Files found by the `where` argument doesn't exist, create a new Files with this data.
   */
  create: Prisma.XOR<Prisma.FilesCreateInput, Prisma.FilesUncheckedCreateInput>
  /**
   * In case the Files was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilesUpdateInput, Prisma.FilesUncheckedUpdateInput>
}

/**
 * Files delete
 */
export type FilesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter which Files to delete.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files deleteMany
 */
export type FilesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Files to delete
   */
  where?: Prisma.FilesWhereInput
  /**
   * Limit how many Files to delete.
   */
  limit?: number
}

/**
 * Files.activityLogs
 */
export type Files$activityLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActivityLogs
   */
  select?: Prisma.ActivityLogsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ActivityLogs
   */
  omit?: Prisma.ActivityLogsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActivityLogsInclude<ExtArgs> | null
  where?: Prisma.ActivityLogsWhereInput
  orderBy?: Prisma.ActivityLogsOrderByWithRelationInput | Prisma.ActivityLogsOrderByWithRelationInput[]
  cursor?: Prisma.ActivityLogsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ActivityLogsScalarFieldEnum | Prisma.ActivityLogsScalarFieldEnum[]
}

/**
 * Files.fileLinks
 */
export type Files$fileLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  where?: Prisma.FileLinkWhereInput
  orderBy?: Prisma.FileLinkOrderByWithRelationInput | Prisma.FileLinkOrderByWithRelationInput[]
  cursor?: Prisma.FileLinkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileLinkScalarFieldEnum | Prisma.FileLinkScalarFieldEnum[]
}

/**
 * Files without action
 */
export type FilesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
}
