
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FileLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FileLink
 * 
 */
export type FileLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$FileLinkPayload>

export type AggregateFileLink = {
  _count: FileLinkCountAggregateOutputType | null
  _min: FileLinkMinAggregateOutputType | null
  _max: FileLinkMaxAggregateOutputType | null
}

export type FileLinkMinAggregateOutputType = {
  id: string | null
  criteriaId: string | null
  fileId: string | null
  criteriaLink: string | null
}

export type FileLinkMaxAggregateOutputType = {
  id: string | null
  criteriaId: string | null
  fileId: string | null
  criteriaLink: string | null
}

export type FileLinkCountAggregateOutputType = {
  id: number
  criteriaId: number
  fileId: number
  criteriaLink: number
  _all: number
}


export type FileLinkMinAggregateInputType = {
  id?: true
  criteriaId?: true
  fileId?: true
  criteriaLink?: true
}

export type FileLinkMaxAggregateInputType = {
  id?: true
  criteriaId?: true
  fileId?: true
  criteriaLink?: true
}

export type FileLinkCountAggregateInputType = {
  id?: true
  criteriaId?: true
  fileId?: true
  criteriaLink?: true
  _all?: true
}

export type FileLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileLink to aggregate.
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileLinks to fetch.
   */
  orderBy?: Prisma.FileLinkOrderByWithRelationInput | Prisma.FileLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FileLinks
  **/
  _count?: true | FileLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileLinkMaxAggregateInputType
}

export type GetFileLinkAggregateType<T extends FileLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateFileLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileLink[P]>
    : Prisma.GetScalarType<T[P], AggregateFileLink[P]>
}




export type FileLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileLinkWhereInput
  orderBy?: Prisma.FileLinkOrderByWithAggregationInput | Prisma.FileLinkOrderByWithAggregationInput[]
  by: Prisma.FileLinkScalarFieldEnum[] | Prisma.FileLinkScalarFieldEnum
  having?: Prisma.FileLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileLinkCountAggregateInputType | true
  _min?: FileLinkMinAggregateInputType
  _max?: FileLinkMaxAggregateInputType
}

export type FileLinkGroupByOutputType = {
  id: string
  criteriaId: string
  fileId: string
  criteriaLink: string
  _count: FileLinkCountAggregateOutputType | null
  _min: FileLinkMinAggregateOutputType | null
  _max: FileLinkMaxAggregateOutputType | null
}

export type GetFileLinkGroupByPayload<T extends FileLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileLinkGroupByOutputType[P]>
      }
    >
  >



export type FileLinkWhereInput = {
  AND?: Prisma.FileLinkWhereInput | Prisma.FileLinkWhereInput[]
  OR?: Prisma.FileLinkWhereInput[]
  NOT?: Prisma.FileLinkWhereInput | Prisma.FileLinkWhereInput[]
  id?: Prisma.StringFilter<"FileLink"> | string
  criteriaId?: Prisma.StringFilter<"FileLink"> | string
  fileId?: Prisma.StringFilter<"FileLink"> | string
  criteriaLink?: Prisma.StringFilter<"FileLink"> | string
  files?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
  criteria?: Prisma.XOR<Prisma.CriteriaScalarRelationFilter, Prisma.CriteriaWhereInput>
}

export type FileLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  criteriaId?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  criteriaLink?: Prisma.SortOrder
  files?: Prisma.FilesOrderByWithRelationInput
  criteria?: Prisma.CriteriaOrderByWithRelationInput
  _relevance?: Prisma.FileLinkOrderByRelevanceInput
}

export type FileLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FileLinkWhereInput | Prisma.FileLinkWhereInput[]
  OR?: Prisma.FileLinkWhereInput[]
  NOT?: Prisma.FileLinkWhereInput | Prisma.FileLinkWhereInput[]
  criteriaId?: Prisma.StringFilter<"FileLink"> | string
  fileId?: Prisma.StringFilter<"FileLink"> | string
  criteriaLink?: Prisma.StringFilter<"FileLink"> | string
  files?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
  criteria?: Prisma.XOR<Prisma.CriteriaScalarRelationFilter, Prisma.CriteriaWhereInput>
}, "id">

export type FileLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  criteriaId?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  criteriaLink?: Prisma.SortOrder
  _count?: Prisma.FileLinkCountOrderByAggregateInput
  _max?: Prisma.FileLinkMaxOrderByAggregateInput
  _min?: Prisma.FileLinkMinOrderByAggregateInput
}

export type FileLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileLinkScalarWhereWithAggregatesInput | Prisma.FileLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileLinkScalarWhereWithAggregatesInput | Prisma.FileLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FileLink"> | string
  criteriaId?: Prisma.StringWithAggregatesFilter<"FileLink"> | string
  fileId?: Prisma.StringWithAggregatesFilter<"FileLink"> | string
  criteriaLink?: Prisma.StringWithAggregatesFilter<"FileLink"> | string
}

export type FileLinkCreateInput = {
  id?: string
  criteriaLink: string
  files: Prisma.FilesCreateNestedOneWithoutFileLinksInput
  criteria: Prisma.CriteriaCreateNestedOneWithoutFileLinksInput
}

export type FileLinkUncheckedCreateInput = {
  id?: string
  criteriaId: string
  fileId: string
  criteriaLink: string
}

export type FileLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.FilesUpdateOneRequiredWithoutFileLinksNestedInput
  criteria?: Prisma.CriteriaUpdateOneRequiredWithoutFileLinksNestedInput
}

export type FileLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaId?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkCreateManyInput = {
  id?: string
  criteriaId: string
  fileId: string
  criteriaLink: string
}

export type FileLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaId?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkListRelationFilter = {
  every?: Prisma.FileLinkWhereInput
  some?: Prisma.FileLinkWhereInput
  none?: Prisma.FileLinkWhereInput
}

export type FileLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FileLinkOrderByRelevanceInput = {
  fields: Prisma.FileLinkOrderByRelevanceFieldEnum | Prisma.FileLinkOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FileLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  criteriaId?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  criteriaLink?: Prisma.SortOrder
}

export type FileLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  criteriaId?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  criteriaLink?: Prisma.SortOrder
}

export type FileLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  criteriaId?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  criteriaLink?: Prisma.SortOrder
}

export type FileLinkCreateNestedManyWithoutCriteriaInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput> | Prisma.FileLinkCreateWithoutCriteriaInput[] | Prisma.FileLinkUncheckedCreateWithoutCriteriaInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutCriteriaInput | Prisma.FileLinkCreateOrConnectWithoutCriteriaInput[]
  createMany?: Prisma.FileLinkCreateManyCriteriaInputEnvelope
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
}

export type FileLinkUncheckedCreateNestedManyWithoutCriteriaInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput> | Prisma.FileLinkCreateWithoutCriteriaInput[] | Prisma.FileLinkUncheckedCreateWithoutCriteriaInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutCriteriaInput | Prisma.FileLinkCreateOrConnectWithoutCriteriaInput[]
  createMany?: Prisma.FileLinkCreateManyCriteriaInputEnvelope
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
}

export type FileLinkUpdateManyWithoutCriteriaNestedInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput> | Prisma.FileLinkCreateWithoutCriteriaInput[] | Prisma.FileLinkUncheckedCreateWithoutCriteriaInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutCriteriaInput | Prisma.FileLinkCreateOrConnectWithoutCriteriaInput[]
  upsert?: Prisma.FileLinkUpsertWithWhereUniqueWithoutCriteriaInput | Prisma.FileLinkUpsertWithWhereUniqueWithoutCriteriaInput[]
  createMany?: Prisma.FileLinkCreateManyCriteriaInputEnvelope
  set?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  disconnect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  delete?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  update?: Prisma.FileLinkUpdateWithWhereUniqueWithoutCriteriaInput | Prisma.FileLinkUpdateWithWhereUniqueWithoutCriteriaInput[]
  updateMany?: Prisma.FileLinkUpdateManyWithWhereWithoutCriteriaInput | Prisma.FileLinkUpdateManyWithWhereWithoutCriteriaInput[]
  deleteMany?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
}

export type FileLinkUncheckedUpdateManyWithoutCriteriaNestedInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput> | Prisma.FileLinkCreateWithoutCriteriaInput[] | Prisma.FileLinkUncheckedCreateWithoutCriteriaInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutCriteriaInput | Prisma.FileLinkCreateOrConnectWithoutCriteriaInput[]
  upsert?: Prisma.FileLinkUpsertWithWhereUniqueWithoutCriteriaInput | Prisma.FileLinkUpsertWithWhereUniqueWithoutCriteriaInput[]
  createMany?: Prisma.FileLinkCreateManyCriteriaInputEnvelope
  set?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  disconnect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  delete?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  update?: Prisma.FileLinkUpdateWithWhereUniqueWithoutCriteriaInput | Prisma.FileLinkUpdateWithWhereUniqueWithoutCriteriaInput[]
  updateMany?: Prisma.FileLinkUpdateManyWithWhereWithoutCriteriaInput | Prisma.FileLinkUpdateManyWithWhereWithoutCriteriaInput[]
  deleteMany?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
}

export type FileLinkCreateNestedManyWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput> | Prisma.FileLinkCreateWithoutFilesInput[] | Prisma.FileLinkUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutFilesInput | Prisma.FileLinkCreateOrConnectWithoutFilesInput[]
  createMany?: Prisma.FileLinkCreateManyFilesInputEnvelope
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
}

export type FileLinkUncheckedCreateNestedManyWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput> | Prisma.FileLinkCreateWithoutFilesInput[] | Prisma.FileLinkUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutFilesInput | Prisma.FileLinkCreateOrConnectWithoutFilesInput[]
  createMany?: Prisma.FileLinkCreateManyFilesInputEnvelope
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
}

export type FileLinkUpdateManyWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput> | Prisma.FileLinkCreateWithoutFilesInput[] | Prisma.FileLinkUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutFilesInput | Prisma.FileLinkCreateOrConnectWithoutFilesInput[]
  upsert?: Prisma.FileLinkUpsertWithWhereUniqueWithoutFilesInput | Prisma.FileLinkUpsertWithWhereUniqueWithoutFilesInput[]
  createMany?: Prisma.FileLinkCreateManyFilesInputEnvelope
  set?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  disconnect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  delete?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  update?: Prisma.FileLinkUpdateWithWhereUniqueWithoutFilesInput | Prisma.FileLinkUpdateWithWhereUniqueWithoutFilesInput[]
  updateMany?: Prisma.FileLinkUpdateManyWithWhereWithoutFilesInput | Prisma.FileLinkUpdateManyWithWhereWithoutFilesInput[]
  deleteMany?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
}

export type FileLinkUncheckedUpdateManyWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput> | Prisma.FileLinkCreateWithoutFilesInput[] | Prisma.FileLinkUncheckedCreateWithoutFilesInput[]
  connectOrCreate?: Prisma.FileLinkCreateOrConnectWithoutFilesInput | Prisma.FileLinkCreateOrConnectWithoutFilesInput[]
  upsert?: Prisma.FileLinkUpsertWithWhereUniqueWithoutFilesInput | Prisma.FileLinkUpsertWithWhereUniqueWithoutFilesInput[]
  createMany?: Prisma.FileLinkCreateManyFilesInputEnvelope
  set?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  disconnect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  delete?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  connect?: Prisma.FileLinkWhereUniqueInput | Prisma.FileLinkWhereUniqueInput[]
  update?: Prisma.FileLinkUpdateWithWhereUniqueWithoutFilesInput | Prisma.FileLinkUpdateWithWhereUniqueWithoutFilesInput[]
  updateMany?: Prisma.FileLinkUpdateManyWithWhereWithoutFilesInput | Prisma.FileLinkUpdateManyWithWhereWithoutFilesInput[]
  deleteMany?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
}

export type FileLinkCreateWithoutCriteriaInput = {
  id?: string
  criteriaLink: string
  files: Prisma.FilesCreateNestedOneWithoutFileLinksInput
}

export type FileLinkUncheckedCreateWithoutCriteriaInput = {
  id?: string
  fileId: string
  criteriaLink: string
}

export type FileLinkCreateOrConnectWithoutCriteriaInput = {
  where: Prisma.FileLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput>
}

export type FileLinkCreateManyCriteriaInputEnvelope = {
  data: Prisma.FileLinkCreateManyCriteriaInput | Prisma.FileLinkCreateManyCriteriaInput[]
  skipDuplicates?: boolean
}

export type FileLinkUpsertWithWhereUniqueWithoutCriteriaInput = {
  where: Prisma.FileLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.FileLinkUpdateWithoutCriteriaInput, Prisma.FileLinkUncheckedUpdateWithoutCriteriaInput>
  create: Prisma.XOR<Prisma.FileLinkCreateWithoutCriteriaInput, Prisma.FileLinkUncheckedCreateWithoutCriteriaInput>
}

export type FileLinkUpdateWithWhereUniqueWithoutCriteriaInput = {
  where: Prisma.FileLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.FileLinkUpdateWithoutCriteriaInput, Prisma.FileLinkUncheckedUpdateWithoutCriteriaInput>
}

export type FileLinkUpdateManyWithWhereWithoutCriteriaInput = {
  where: Prisma.FileLinkScalarWhereInput
  data: Prisma.XOR<Prisma.FileLinkUpdateManyMutationInput, Prisma.FileLinkUncheckedUpdateManyWithoutCriteriaInput>
}

export type FileLinkScalarWhereInput = {
  AND?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
  OR?: Prisma.FileLinkScalarWhereInput[]
  NOT?: Prisma.FileLinkScalarWhereInput | Prisma.FileLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"FileLink"> | string
  criteriaId?: Prisma.StringFilter<"FileLink"> | string
  fileId?: Prisma.StringFilter<"FileLink"> | string
  criteriaLink?: Prisma.StringFilter<"FileLink"> | string
}

export type FileLinkCreateWithoutFilesInput = {
  id?: string
  criteriaLink: string
  criteria: Prisma.CriteriaCreateNestedOneWithoutFileLinksInput
}

export type FileLinkUncheckedCreateWithoutFilesInput = {
  id?: string
  criteriaId: string
  criteriaLink: string
}

export type FileLinkCreateOrConnectWithoutFilesInput = {
  where: Prisma.FileLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput>
}

export type FileLinkCreateManyFilesInputEnvelope = {
  data: Prisma.FileLinkCreateManyFilesInput | Prisma.FileLinkCreateManyFilesInput[]
  skipDuplicates?: boolean
}

export type FileLinkUpsertWithWhereUniqueWithoutFilesInput = {
  where: Prisma.FileLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.FileLinkUpdateWithoutFilesInput, Prisma.FileLinkUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.FileLinkCreateWithoutFilesInput, Prisma.FileLinkUncheckedCreateWithoutFilesInput>
}

export type FileLinkUpdateWithWhereUniqueWithoutFilesInput = {
  where: Prisma.FileLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.FileLinkUpdateWithoutFilesInput, Prisma.FileLinkUncheckedUpdateWithoutFilesInput>
}

export type FileLinkUpdateManyWithWhereWithoutFilesInput = {
  where: Prisma.FileLinkScalarWhereInput
  data: Prisma.XOR<Prisma.FileLinkUpdateManyMutationInput, Prisma.FileLinkUncheckedUpdateManyWithoutFilesInput>
}

export type FileLinkCreateManyCriteriaInput = {
  id?: string
  fileId: string
  criteriaLink: string
}

export type FileLinkUpdateWithoutCriteriaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
  files?: Prisma.FilesUpdateOneRequiredWithoutFileLinksNestedInput
}

export type FileLinkUncheckedUpdateWithoutCriteriaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkUncheckedUpdateManyWithoutCriteriaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkCreateManyFilesInput = {
  id?: string
  criteriaId: string
  criteriaLink: string
}

export type FileLinkUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
  criteria?: Prisma.CriteriaUpdateOneRequiredWithoutFileLinksNestedInput
}

export type FileLinkUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileLinkUncheckedUpdateManyWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaId?: Prisma.StringFieldUpdateOperationsInput | string
  criteriaLink?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FileLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  criteriaId?: boolean
  fileId?: boolean
  criteriaLink?: boolean
  files?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
  criteria?: boolean | Prisma.CriteriaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileLink"]>



export type FileLinkSelectScalar = {
  id?: boolean
  criteriaId?: boolean
  fileId?: boolean
  criteriaLink?: boolean
}

export type FileLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "criteriaId" | "fileId" | "criteriaLink", ExtArgs["result"]["fileLink"]>
export type FileLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  files?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
  criteria?: boolean | Prisma.CriteriaDefaultArgs<ExtArgs>
}

export type $FileLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FileLink"
  objects: {
    files: Prisma.$FilesPayload<ExtArgs>
    criteria: Prisma.$CriteriaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    criteriaId: string
    fileId: string
    criteriaLink: string
  }, ExtArgs["result"]["fileLink"]>
  composites: {}
}

export type FileLinkGetPayload<S extends boolean | null | undefined | FileLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FileLinkPayload, S>

export type FileLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileLinkCountAggregateInputType | true
  }

export interface FileLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileLink'], meta: { name: 'FileLink' } }
  /**
   * Find zero or one FileLink that matches the filter.
   * @param {FileLinkFindUniqueArgs} args - Arguments to find a FileLink
   * @example
   * // Get one FileLink
   * const fileLink = await prisma.fileLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, FileLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FileLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileLinkFindUniqueOrThrowArgs} args - Arguments to find a FileLink
   * @example
   * // Get one FileLink
   * const fileLink = await prisma.fileLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkFindFirstArgs} args - Arguments to find a FileLink
   * @example
   * // Get one FileLink
   * const fileLink = await prisma.fileLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, FileLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkFindFirstOrThrowArgs} args - Arguments to find a FileLink
   * @example
   * // Get one FileLink
   * const fileLink = await prisma.fileLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FileLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileLinks
   * const fileLinks = await prisma.fileLink.findMany()
   * 
   * // Get first 10 FileLinks
   * const fileLinks = await prisma.fileLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileLinkWithIdOnly = await prisma.fileLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileLinkFindManyArgs>(args?: Prisma.SelectSubset<T, FileLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FileLink.
   * @param {FileLinkCreateArgs} args - Arguments to create a FileLink.
   * @example
   * // Create one FileLink
   * const FileLink = await prisma.fileLink.create({
   *   data: {
   *     // ... data to create a FileLink
   *   }
   * })
   * 
   */
  create<T extends FileLinkCreateArgs>(args: Prisma.SelectSubset<T, FileLinkCreateArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FileLinks.
   * @param {FileLinkCreateManyArgs} args - Arguments to create many FileLinks.
   * @example
   * // Create many FileLinks
   * const fileLink = await prisma.fileLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, FileLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FileLink.
   * @param {FileLinkDeleteArgs} args - Arguments to delete one FileLink.
   * @example
   * // Delete one FileLink
   * const FileLink = await prisma.fileLink.delete({
   *   where: {
   *     // ... filter to delete one FileLink
   *   }
   * })
   * 
   */
  delete<T extends FileLinkDeleteArgs>(args: Prisma.SelectSubset<T, FileLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FileLink.
   * @param {FileLinkUpdateArgs} args - Arguments to update one FileLink.
   * @example
   * // Update one FileLink
   * const fileLink = await prisma.fileLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileLinkUpdateArgs>(args: Prisma.SelectSubset<T, FileLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FileLinks.
   * @param {FileLinkDeleteManyArgs} args - Arguments to filter FileLinks to delete.
   * @example
   * // Delete a few FileLinks
   * const { count } = await prisma.fileLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileLinks
   * const fileLink = await prisma.fileLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, FileLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FileLink.
   * @param {FileLinkUpsertArgs} args - Arguments to update or create a FileLink.
   * @example
   * // Update or create a FileLink
   * const fileLink = await prisma.fileLink.upsert({
   *   create: {
   *     // ... data to create a FileLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileLink we want to update
   *   }
   * })
   */
  upsert<T extends FileLinkUpsertArgs>(args: Prisma.SelectSubset<T, FileLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__FileLinkClient<runtime.Types.Result.GetResult<Prisma.$FileLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FileLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkCountArgs} args - Arguments to filter FileLinks to count.
   * @example
   * // Count the number of FileLinks
   * const count = await prisma.fileLink.count({
   *   where: {
   *     // ... the filter for the FileLinks we want to count
   *   }
   * })
  **/
  count<T extends FileLinkCountArgs>(
    args?: Prisma.Subset<T, FileLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FileLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileLinkAggregateArgs>(args: Prisma.Subset<T, FileLinkAggregateArgs>): Prisma.PrismaPromise<GetFileLinkAggregateType<T>>

  /**
   * Group by FileLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileLinkGroupByArgs['orderBy'] }
      : { orderBy?: FileLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FileLink model
 */
readonly fields: FileLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  files<T extends Prisma.FilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilesDefaultArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  criteria<T extends Prisma.CriteriaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CriteriaDefaultArgs<ExtArgs>>): Prisma.Prisma__CriteriaClient<runtime.Types.Result.GetResult<Prisma.$CriteriaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FileLink model
 */
export interface FileLinkFieldRefs {
  readonly id: Prisma.FieldRef<"FileLink", 'String'>
  readonly criteriaId: Prisma.FieldRef<"FileLink", 'String'>
  readonly fileId: Prisma.FieldRef<"FileLink", 'String'>
  readonly criteriaLink: Prisma.FieldRef<"FileLink", 'String'>
}
    

// Custom InputTypes
/**
 * FileLink findUnique
 */
export type FileLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter, which FileLink to fetch.
   */
  where: Prisma.FileLinkWhereUniqueInput
}

/**
 * FileLink findUniqueOrThrow
 */
export type FileLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter, which FileLink to fetch.
   */
  where: Prisma.FileLinkWhereUniqueInput
}

/**
 * FileLink findFirst
 */
export type FileLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter, which FileLink to fetch.
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileLinks to fetch.
   */
  orderBy?: Prisma.FileLinkOrderByWithRelationInput | Prisma.FileLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileLinks.
   */
  cursor?: Prisma.FileLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileLinks.
   */
  distinct?: Prisma.FileLinkScalarFieldEnum | Prisma.FileLinkScalarFieldEnum[]
}

/**
 * FileLink findFirstOrThrow
 */
export type FileLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter, which FileLink to fetch.
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileLinks to fetch.
   */
  orderBy?: Prisma.FileLinkOrderByWithRelationInput | Prisma.FileLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileLinks.
   */
  cursor?: Prisma.FileLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileLinks.
   */
  distinct?: Prisma.FileLinkScalarFieldEnum | Prisma.FileLinkScalarFieldEnum[]
}

/**
 * FileLink findMany
 */
export type FileLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter, which FileLinks to fetch.
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileLinks to fetch.
   */
  orderBy?: Prisma.FileLinkOrderByWithRelationInput | Prisma.FileLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FileLinks.
   */
  cursor?: Prisma.FileLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileLinks.
   */
  distinct?: Prisma.FileLinkScalarFieldEnum | Prisma.FileLinkScalarFieldEnum[]
}

/**
 * FileLink create
 */
export type FileLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a FileLink.
   */
  data: Prisma.XOR<Prisma.FileLinkCreateInput, Prisma.FileLinkUncheckedCreateInput>
}

/**
 * FileLink createMany
 */
export type FileLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FileLinks.
   */
  data: Prisma.FileLinkCreateManyInput | Prisma.FileLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileLink update
 */
export type FileLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a FileLink.
   */
  data: Prisma.XOR<Prisma.FileLinkUpdateInput, Prisma.FileLinkUncheckedUpdateInput>
  /**
   * Choose, which FileLink to update.
   */
  where: Prisma.FileLinkWhereUniqueInput
}

/**
 * FileLink updateMany
 */
export type FileLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FileLinks.
   */
  data: Prisma.XOR<Prisma.FileLinkUpdateManyMutationInput, Prisma.FileLinkUncheckedUpdateManyInput>
  /**
   * Filter which FileLinks to update
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * Limit how many FileLinks to update.
   */
  limit?: number
}

/**
 * FileLink upsert
 */
export type FileLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the FileLink to update in case it exists.
   */
  where: Prisma.FileLinkWhereUniqueInput
  /**
   * In case the FileLink found by the `where` argument doesn't exist, create a new FileLink with this data.
   */
  create: Prisma.XOR<Prisma.FileLinkCreateInput, Prisma.FileLinkUncheckedCreateInput>
  /**
   * In case the FileLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileLinkUpdateInput, Prisma.FileLinkUncheckedUpdateInput>
}

/**
 * FileLink delete
 */
export type FileLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
  /**
   * Filter which FileLink to delete.
   */
  where: Prisma.FileLinkWhereUniqueInput
}

/**
 * FileLink deleteMany
 */
export type FileLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileLinks to delete
   */
  where?: Prisma.FileLinkWhereInput
  /**
   * Limit how many FileLinks to delete.
   */
  limit?: number
}

/**
 * FileLink without action
 */
export type FileLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileLink
   */
  select?: Prisma.FileLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileLink
   */
  omit?: Prisma.FileLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileLinkInclude<ExtArgs> | null
}
