
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MajorAccess` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MajorAccess
 * 
 */
export type MajorAccessModel = runtime.Types.Result.DefaultSelection<Prisma.$MajorAccessPayload>

export type AggregateMajorAccess = {
  _count: MajorAccessCountAggregateOutputType | null
  _min: MajorAccessMinAggregateOutputType | null
  _max: MajorAccessMaxAggregateOutputType | null
}

export type MajorAccessMinAggregateOutputType = {
  id: string | null
  userId: string | null
  majorId: string | null
}

export type MajorAccessMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  majorId: string | null
}

export type MajorAccessCountAggregateOutputType = {
  id: number
  userId: number
  majorId: number
  _all: number
}


export type MajorAccessMinAggregateInputType = {
  id?: true
  userId?: true
  majorId?: true
}

export type MajorAccessMaxAggregateInputType = {
  id?: true
  userId?: true
  majorId?: true
}

export type MajorAccessCountAggregateInputType = {
  id?: true
  userId?: true
  majorId?: true
  _all?: true
}

export type MajorAccessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MajorAccess to aggregate.
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MajorAccesses to fetch.
   */
  orderBy?: Prisma.MajorAccessOrderByWithRelationInput | Prisma.MajorAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MajorAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MajorAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MajorAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MajorAccesses
  **/
  _count?: true | MajorAccessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MajorAccessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MajorAccessMaxAggregateInputType
}

export type GetMajorAccessAggregateType<T extends MajorAccessAggregateArgs> = {
      [P in keyof T & keyof AggregateMajorAccess]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMajorAccess[P]>
    : Prisma.GetScalarType<T[P], AggregateMajorAccess[P]>
}




export type MajorAccessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MajorAccessWhereInput
  orderBy?: Prisma.MajorAccessOrderByWithAggregationInput | Prisma.MajorAccessOrderByWithAggregationInput[]
  by: Prisma.MajorAccessScalarFieldEnum[] | Prisma.MajorAccessScalarFieldEnum
  having?: Prisma.MajorAccessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MajorAccessCountAggregateInputType | true
  _min?: MajorAccessMinAggregateInputType
  _max?: MajorAccessMaxAggregateInputType
}

export type MajorAccessGroupByOutputType = {
  id: string
  userId: string
  majorId: string
  _count: MajorAccessCountAggregateOutputType | null
  _min: MajorAccessMinAggregateOutputType | null
  _max: MajorAccessMaxAggregateOutputType | null
}

export type GetMajorAccessGroupByPayload<T extends MajorAccessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MajorAccessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MajorAccessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MajorAccessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MajorAccessGroupByOutputType[P]>
      }
    >
  >



export type MajorAccessWhereInput = {
  AND?: Prisma.MajorAccessWhereInput | Prisma.MajorAccessWhereInput[]
  OR?: Prisma.MajorAccessWhereInput[]
  NOT?: Prisma.MajorAccessWhereInput | Prisma.MajorAccessWhereInput[]
  id?: Prisma.StringFilter<"MajorAccess"> | string
  userId?: Prisma.StringFilter<"MajorAccess"> | string
  majorId?: Prisma.StringFilter<"MajorAccess"> | string
  majors?: Prisma.XOR<Prisma.MajorsScalarRelationFilter, Prisma.MajorsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
}

export type MajorAccessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  majors?: Prisma.MajorsOrderByWithRelationInput
  users?: Prisma.UsersOrderByWithRelationInput
  _relevance?: Prisma.MajorAccessOrderByRelevanceInput
}

export type MajorAccessWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MajorAccessWhereInput | Prisma.MajorAccessWhereInput[]
  OR?: Prisma.MajorAccessWhereInput[]
  NOT?: Prisma.MajorAccessWhereInput | Prisma.MajorAccessWhereInput[]
  userId?: Prisma.StringFilter<"MajorAccess"> | string
  majorId?: Prisma.StringFilter<"MajorAccess"> | string
  majors?: Prisma.XOR<Prisma.MajorsScalarRelationFilter, Prisma.MajorsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
}, "id">

export type MajorAccessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  _count?: Prisma.MajorAccessCountOrderByAggregateInput
  _max?: Prisma.MajorAccessMaxOrderByAggregateInput
  _min?: Prisma.MajorAccessMinOrderByAggregateInput
}

export type MajorAccessScalarWhereWithAggregatesInput = {
  AND?: Prisma.MajorAccessScalarWhereWithAggregatesInput | Prisma.MajorAccessScalarWhereWithAggregatesInput[]
  OR?: Prisma.MajorAccessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MajorAccessScalarWhereWithAggregatesInput | Prisma.MajorAccessScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MajorAccess"> | string
  userId?: Prisma.StringWithAggregatesFilter<"MajorAccess"> | string
  majorId?: Prisma.StringWithAggregatesFilter<"MajorAccess"> | string
}

export type MajorAccessCreateInput = {
  id?: string
  majors: Prisma.MajorsCreateNestedOneWithoutMajorAccessesInput
  users: Prisma.UsersCreateNestedOneWithoutMajorAccessInput
}

export type MajorAccessUncheckedCreateInput = {
  id?: string
  userId: string
  majorId: string
}

export type MajorAccessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majors?: Prisma.MajorsUpdateOneRequiredWithoutMajorAccessesNestedInput
  users?: Prisma.UsersUpdateOneRequiredWithoutMajorAccessNestedInput
}

export type MajorAccessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessCreateManyInput = {
  id?: string
  userId: string
  majorId: string
}

export type MajorAccessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessListRelationFilter = {
  every?: Prisma.MajorAccessWhereInput
  some?: Prisma.MajorAccessWhereInput
  none?: Prisma.MajorAccessWhereInput
}

export type MajorAccessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MajorAccessOrderByRelevanceInput = {
  fields: Prisma.MajorAccessOrderByRelevanceFieldEnum | Prisma.MajorAccessOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type MajorAccessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type MajorAccessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type MajorAccessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type MajorAccessCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput> | Prisma.MajorAccessCreateWithoutUsersInput[] | Prisma.MajorAccessUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutUsersInput | Prisma.MajorAccessCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MajorAccessCreateManyUsersInputEnvelope
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
}

export type MajorAccessUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput> | Prisma.MajorAccessCreateWithoutUsersInput[] | Prisma.MajorAccessUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutUsersInput | Prisma.MajorAccessCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MajorAccessCreateManyUsersInputEnvelope
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
}

export type MajorAccessUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput> | Prisma.MajorAccessCreateWithoutUsersInput[] | Prisma.MajorAccessUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutUsersInput | Prisma.MajorAccessCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MajorAccessUpsertWithWhereUniqueWithoutUsersInput | Prisma.MajorAccessUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MajorAccessCreateManyUsersInputEnvelope
  set?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  disconnect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  delete?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  update?: Prisma.MajorAccessUpdateWithWhereUniqueWithoutUsersInput | Prisma.MajorAccessUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MajorAccessUpdateManyWithWhereWithoutUsersInput | Prisma.MajorAccessUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
}

export type MajorAccessUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput> | Prisma.MajorAccessCreateWithoutUsersInput[] | Prisma.MajorAccessUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutUsersInput | Prisma.MajorAccessCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MajorAccessUpsertWithWhereUniqueWithoutUsersInput | Prisma.MajorAccessUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MajorAccessCreateManyUsersInputEnvelope
  set?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  disconnect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  delete?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  update?: Prisma.MajorAccessUpdateWithWhereUniqueWithoutUsersInput | Prisma.MajorAccessUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MajorAccessUpdateManyWithWhereWithoutUsersInput | Prisma.MajorAccessUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
}

export type MajorAccessCreateNestedManyWithoutMajorsInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput> | Prisma.MajorAccessCreateWithoutMajorsInput[] | Prisma.MajorAccessUncheckedCreateWithoutMajorsInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutMajorsInput | Prisma.MajorAccessCreateOrConnectWithoutMajorsInput[]
  createMany?: Prisma.MajorAccessCreateManyMajorsInputEnvelope
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
}

export type MajorAccessUncheckedCreateNestedManyWithoutMajorsInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput> | Prisma.MajorAccessCreateWithoutMajorsInput[] | Prisma.MajorAccessUncheckedCreateWithoutMajorsInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutMajorsInput | Prisma.MajorAccessCreateOrConnectWithoutMajorsInput[]
  createMany?: Prisma.MajorAccessCreateManyMajorsInputEnvelope
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
}

export type MajorAccessUpdateManyWithoutMajorsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput> | Prisma.MajorAccessCreateWithoutMajorsInput[] | Prisma.MajorAccessUncheckedCreateWithoutMajorsInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutMajorsInput | Prisma.MajorAccessCreateOrConnectWithoutMajorsInput[]
  upsert?: Prisma.MajorAccessUpsertWithWhereUniqueWithoutMajorsInput | Prisma.MajorAccessUpsertWithWhereUniqueWithoutMajorsInput[]
  createMany?: Prisma.MajorAccessCreateManyMajorsInputEnvelope
  set?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  disconnect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  delete?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  update?: Prisma.MajorAccessUpdateWithWhereUniqueWithoutMajorsInput | Prisma.MajorAccessUpdateWithWhereUniqueWithoutMajorsInput[]
  updateMany?: Prisma.MajorAccessUpdateManyWithWhereWithoutMajorsInput | Prisma.MajorAccessUpdateManyWithWhereWithoutMajorsInput[]
  deleteMany?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
}

export type MajorAccessUncheckedUpdateManyWithoutMajorsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput> | Prisma.MajorAccessCreateWithoutMajorsInput[] | Prisma.MajorAccessUncheckedCreateWithoutMajorsInput[]
  connectOrCreate?: Prisma.MajorAccessCreateOrConnectWithoutMajorsInput | Prisma.MajorAccessCreateOrConnectWithoutMajorsInput[]
  upsert?: Prisma.MajorAccessUpsertWithWhereUniqueWithoutMajorsInput | Prisma.MajorAccessUpsertWithWhereUniqueWithoutMajorsInput[]
  createMany?: Prisma.MajorAccessCreateManyMajorsInputEnvelope
  set?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  disconnect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  delete?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  connect?: Prisma.MajorAccessWhereUniqueInput | Prisma.MajorAccessWhereUniqueInput[]
  update?: Prisma.MajorAccessUpdateWithWhereUniqueWithoutMajorsInput | Prisma.MajorAccessUpdateWithWhereUniqueWithoutMajorsInput[]
  updateMany?: Prisma.MajorAccessUpdateManyWithWhereWithoutMajorsInput | Prisma.MajorAccessUpdateManyWithWhereWithoutMajorsInput[]
  deleteMany?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
}

export type MajorAccessCreateWithoutUsersInput = {
  id?: string
  majors: Prisma.MajorsCreateNestedOneWithoutMajorAccessesInput
}

export type MajorAccessUncheckedCreateWithoutUsersInput = {
  id?: string
  majorId: string
}

export type MajorAccessCreateOrConnectWithoutUsersInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput>
}

export type MajorAccessCreateManyUsersInputEnvelope = {
  data: Prisma.MajorAccessCreateManyUsersInput | Prisma.MajorAccessCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type MajorAccessUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.MajorAccessUpdateWithoutUsersInput, Prisma.MajorAccessUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.MajorAccessCreateWithoutUsersInput, Prisma.MajorAccessUncheckedCreateWithoutUsersInput>
}

export type MajorAccessUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.MajorAccessUpdateWithoutUsersInput, Prisma.MajorAccessUncheckedUpdateWithoutUsersInput>
}

export type MajorAccessUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.MajorAccessScalarWhereInput
  data: Prisma.XOR<Prisma.MajorAccessUpdateManyMutationInput, Prisma.MajorAccessUncheckedUpdateManyWithoutUsersInput>
}

export type MajorAccessScalarWhereInput = {
  AND?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
  OR?: Prisma.MajorAccessScalarWhereInput[]
  NOT?: Prisma.MajorAccessScalarWhereInput | Prisma.MajorAccessScalarWhereInput[]
  id?: Prisma.StringFilter<"MajorAccess"> | string
  userId?: Prisma.StringFilter<"MajorAccess"> | string
  majorId?: Prisma.StringFilter<"MajorAccess"> | string
}

export type MajorAccessCreateWithoutMajorsInput = {
  id?: string
  users: Prisma.UsersCreateNestedOneWithoutMajorAccessInput
}

export type MajorAccessUncheckedCreateWithoutMajorsInput = {
  id?: string
  userId: string
}

export type MajorAccessCreateOrConnectWithoutMajorsInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput>
}

export type MajorAccessCreateManyMajorsInputEnvelope = {
  data: Prisma.MajorAccessCreateManyMajorsInput | Prisma.MajorAccessCreateManyMajorsInput[]
  skipDuplicates?: boolean
}

export type MajorAccessUpsertWithWhereUniqueWithoutMajorsInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.MajorAccessUpdateWithoutMajorsInput, Prisma.MajorAccessUncheckedUpdateWithoutMajorsInput>
  create: Prisma.XOR<Prisma.MajorAccessCreateWithoutMajorsInput, Prisma.MajorAccessUncheckedCreateWithoutMajorsInput>
}

export type MajorAccessUpdateWithWhereUniqueWithoutMajorsInput = {
  where: Prisma.MajorAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.MajorAccessUpdateWithoutMajorsInput, Prisma.MajorAccessUncheckedUpdateWithoutMajorsInput>
}

export type MajorAccessUpdateManyWithWhereWithoutMajorsInput = {
  where: Prisma.MajorAccessScalarWhereInput
  data: Prisma.XOR<Prisma.MajorAccessUpdateManyMutationInput, Prisma.MajorAccessUncheckedUpdateManyWithoutMajorsInput>
}

export type MajorAccessCreateManyUsersInput = {
  id?: string
  majorId: string
}

export type MajorAccessUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majors?: Prisma.MajorsUpdateOneRequiredWithoutMajorAccessesNestedInput
}

export type MajorAccessUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessCreateManyMajorsInput = {
  id?: string
  userId: string
}

export type MajorAccessUpdateWithoutMajorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  users?: Prisma.UsersUpdateOneRequiredWithoutMajorAccessNestedInput
}

export type MajorAccessUncheckedUpdateWithoutMajorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MajorAccessUncheckedUpdateManyWithoutMajorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type MajorAccessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  majorId?: boolean
  majors?: boolean | Prisma.MajorsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["majorAccess"]>



export type MajorAccessSelectScalar = {
  id?: boolean
  userId?: boolean
  majorId?: boolean
}

export type MajorAccessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "majorId", ExtArgs["result"]["majorAccess"]>
export type MajorAccessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  majors?: boolean | Prisma.MajorsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
}

export type $MajorAccessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MajorAccess"
  objects: {
    majors: Prisma.$MajorsPayload<ExtArgs>
    users: Prisma.$UsersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    majorId: string
  }, ExtArgs["result"]["majorAccess"]>
  composites: {}
}

export type MajorAccessGetPayload<S extends boolean | null | undefined | MajorAccessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload, S>

export type MajorAccessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MajorAccessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MajorAccessCountAggregateInputType | true
  }

export interface MajorAccessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MajorAccess'], meta: { name: 'MajorAccess' } }
  /**
   * Find zero or one MajorAccess that matches the filter.
   * @param {MajorAccessFindUniqueArgs} args - Arguments to find a MajorAccess
   * @example
   * // Get one MajorAccess
   * const majorAccess = await prisma.majorAccess.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MajorAccessFindUniqueArgs>(args: Prisma.SelectSubset<T, MajorAccessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MajorAccess that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MajorAccessFindUniqueOrThrowArgs} args - Arguments to find a MajorAccess
   * @example
   * // Get one MajorAccess
   * const majorAccess = await prisma.majorAccess.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MajorAccessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MajorAccessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MajorAccess that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessFindFirstArgs} args - Arguments to find a MajorAccess
   * @example
   * // Get one MajorAccess
   * const majorAccess = await prisma.majorAccess.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MajorAccessFindFirstArgs>(args?: Prisma.SelectSubset<T, MajorAccessFindFirstArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MajorAccess that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessFindFirstOrThrowArgs} args - Arguments to find a MajorAccess
   * @example
   * // Get one MajorAccess
   * const majorAccess = await prisma.majorAccess.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MajorAccessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MajorAccessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MajorAccesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MajorAccesses
   * const majorAccesses = await prisma.majorAccess.findMany()
   * 
   * // Get first 10 MajorAccesses
   * const majorAccesses = await prisma.majorAccess.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const majorAccessWithIdOnly = await prisma.majorAccess.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MajorAccessFindManyArgs>(args?: Prisma.SelectSubset<T, MajorAccessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MajorAccess.
   * @param {MajorAccessCreateArgs} args - Arguments to create a MajorAccess.
   * @example
   * // Create one MajorAccess
   * const MajorAccess = await prisma.majorAccess.create({
   *   data: {
   *     // ... data to create a MajorAccess
   *   }
   * })
   * 
   */
  create<T extends MajorAccessCreateArgs>(args: Prisma.SelectSubset<T, MajorAccessCreateArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MajorAccesses.
   * @param {MajorAccessCreateManyArgs} args - Arguments to create many MajorAccesses.
   * @example
   * // Create many MajorAccesses
   * const majorAccess = await prisma.majorAccess.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MajorAccessCreateManyArgs>(args?: Prisma.SelectSubset<T, MajorAccessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a MajorAccess.
   * @param {MajorAccessDeleteArgs} args - Arguments to delete one MajorAccess.
   * @example
   * // Delete one MajorAccess
   * const MajorAccess = await prisma.majorAccess.delete({
   *   where: {
   *     // ... filter to delete one MajorAccess
   *   }
   * })
   * 
   */
  delete<T extends MajorAccessDeleteArgs>(args: Prisma.SelectSubset<T, MajorAccessDeleteArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MajorAccess.
   * @param {MajorAccessUpdateArgs} args - Arguments to update one MajorAccess.
   * @example
   * // Update one MajorAccess
   * const majorAccess = await prisma.majorAccess.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MajorAccessUpdateArgs>(args: Prisma.SelectSubset<T, MajorAccessUpdateArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MajorAccesses.
   * @param {MajorAccessDeleteManyArgs} args - Arguments to filter MajorAccesses to delete.
   * @example
   * // Delete a few MajorAccesses
   * const { count } = await prisma.majorAccess.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MajorAccessDeleteManyArgs>(args?: Prisma.SelectSubset<T, MajorAccessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MajorAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MajorAccesses
   * const majorAccess = await prisma.majorAccess.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MajorAccessUpdateManyArgs>(args: Prisma.SelectSubset<T, MajorAccessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one MajorAccess.
   * @param {MajorAccessUpsertArgs} args - Arguments to update or create a MajorAccess.
   * @example
   * // Update or create a MajorAccess
   * const majorAccess = await prisma.majorAccess.upsert({
   *   create: {
   *     // ... data to create a MajorAccess
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MajorAccess we want to update
   *   }
   * })
   */
  upsert<T extends MajorAccessUpsertArgs>(args: Prisma.SelectSubset<T, MajorAccessUpsertArgs<ExtArgs>>): Prisma.Prisma__MajorAccessClient<runtime.Types.Result.GetResult<Prisma.$MajorAccessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MajorAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessCountArgs} args - Arguments to filter MajorAccesses to count.
   * @example
   * // Count the number of MajorAccesses
   * const count = await prisma.majorAccess.count({
   *   where: {
   *     // ... the filter for the MajorAccesses we want to count
   *   }
   * })
  **/
  count<T extends MajorAccessCountArgs>(
    args?: Prisma.Subset<T, MajorAccessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MajorAccessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MajorAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MajorAccessAggregateArgs>(args: Prisma.Subset<T, MajorAccessAggregateArgs>): Prisma.PrismaPromise<GetMajorAccessAggregateType<T>>

  /**
   * Group by MajorAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAccessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MajorAccessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MajorAccessGroupByArgs['orderBy'] }
      : { orderBy?: MajorAccessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MajorAccessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMajorAccessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MajorAccess model
 */
readonly fields: MajorAccessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MajorAccess.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MajorAccessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  majors<T extends Prisma.MajorsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MajorsDefaultArgs<ExtArgs>>): Prisma.Prisma__MajorsClient<runtime.Types.Result.GetResult<Prisma.$MajorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MajorAccess model
 */
export interface MajorAccessFieldRefs {
  readonly id: Prisma.FieldRef<"MajorAccess", 'String'>
  readonly userId: Prisma.FieldRef<"MajorAccess", 'String'>
  readonly majorId: Prisma.FieldRef<"MajorAccess", 'String'>
}
    

// Custom InputTypes
/**
 * MajorAccess findUnique
 */
export type MajorAccessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter, which MajorAccess to fetch.
   */
  where: Prisma.MajorAccessWhereUniqueInput
}

/**
 * MajorAccess findUniqueOrThrow
 */
export type MajorAccessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter, which MajorAccess to fetch.
   */
  where: Prisma.MajorAccessWhereUniqueInput
}

/**
 * MajorAccess findFirst
 */
export type MajorAccessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter, which MajorAccess to fetch.
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MajorAccesses to fetch.
   */
  orderBy?: Prisma.MajorAccessOrderByWithRelationInput | Prisma.MajorAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MajorAccesses.
   */
  cursor?: Prisma.MajorAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MajorAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MajorAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MajorAccesses.
   */
  distinct?: Prisma.MajorAccessScalarFieldEnum | Prisma.MajorAccessScalarFieldEnum[]
}

/**
 * MajorAccess findFirstOrThrow
 */
export type MajorAccessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter, which MajorAccess to fetch.
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MajorAccesses to fetch.
   */
  orderBy?: Prisma.MajorAccessOrderByWithRelationInput | Prisma.MajorAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MajorAccesses.
   */
  cursor?: Prisma.MajorAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MajorAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MajorAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MajorAccesses.
   */
  distinct?: Prisma.MajorAccessScalarFieldEnum | Prisma.MajorAccessScalarFieldEnum[]
}

/**
 * MajorAccess findMany
 */
export type MajorAccessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter, which MajorAccesses to fetch.
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MajorAccesses to fetch.
   */
  orderBy?: Prisma.MajorAccessOrderByWithRelationInput | Prisma.MajorAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MajorAccesses.
   */
  cursor?: Prisma.MajorAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MajorAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MajorAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MajorAccesses.
   */
  distinct?: Prisma.MajorAccessScalarFieldEnum | Prisma.MajorAccessScalarFieldEnum[]
}

/**
 * MajorAccess create
 */
export type MajorAccessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * The data needed to create a MajorAccess.
   */
  data: Prisma.XOR<Prisma.MajorAccessCreateInput, Prisma.MajorAccessUncheckedCreateInput>
}

/**
 * MajorAccess createMany
 */
export type MajorAccessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MajorAccesses.
   */
  data: Prisma.MajorAccessCreateManyInput | Prisma.MajorAccessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MajorAccess update
 */
export type MajorAccessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * The data needed to update a MajorAccess.
   */
  data: Prisma.XOR<Prisma.MajorAccessUpdateInput, Prisma.MajorAccessUncheckedUpdateInput>
  /**
   * Choose, which MajorAccess to update.
   */
  where: Prisma.MajorAccessWhereUniqueInput
}

/**
 * MajorAccess updateMany
 */
export type MajorAccessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MajorAccesses.
   */
  data: Prisma.XOR<Prisma.MajorAccessUpdateManyMutationInput, Prisma.MajorAccessUncheckedUpdateManyInput>
  /**
   * Filter which MajorAccesses to update
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * Limit how many MajorAccesses to update.
   */
  limit?: number
}

/**
 * MajorAccess upsert
 */
export type MajorAccessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * The filter to search for the MajorAccess to update in case it exists.
   */
  where: Prisma.MajorAccessWhereUniqueInput
  /**
   * In case the MajorAccess found by the `where` argument doesn't exist, create a new MajorAccess with this data.
   */
  create: Prisma.XOR<Prisma.MajorAccessCreateInput, Prisma.MajorAccessUncheckedCreateInput>
  /**
   * In case the MajorAccess was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MajorAccessUpdateInput, Prisma.MajorAccessUncheckedUpdateInput>
}

/**
 * MajorAccess delete
 */
export type MajorAccessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
  /**
   * Filter which MajorAccess to delete.
   */
  where: Prisma.MajorAccessWhereUniqueInput
}

/**
 * MajorAccess deleteMany
 */
export type MajorAccessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MajorAccesses to delete
   */
  where?: Prisma.MajorAccessWhereInput
  /**
   * Limit how many MajorAccesses to delete.
   */
  limit?: number
}

/**
 * MajorAccess without action
 */
export type MajorAccessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorAccess
   */
  select?: Prisma.MajorAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MajorAccess
   */
  omit?: Prisma.MajorAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorAccessInclude<ExtArgs> | null
}
