/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as authUserDashboardRouteImport } from './routes/(auth)/user/dashboard'
import { Route as authAsesorDashboardRouteImport } from './routes/(auth)/asesor/dashboard'
import { Route as authAdminDashboardRouteImport } from './routes/(auth)/admin/dashboard'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const authUserDashboardRoute = authUserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authAsesorDashboardRoute = authAsesorDashboardRouteImport.update({
  id: '/asesor/dashboard',
  path: '/asesor/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authAdminDashboardRoute = authAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/login': typeof publicLoginRoute
  '/admin/dashboard': typeof authAdminDashboardRoute
  '/asesor/dashboard': typeof authAsesorDashboardRoute
  '/user/dashboard': typeof authUserDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/login': typeof publicLoginRoute
  '/admin/dashboard': typeof authAdminDashboardRoute
  '/asesor/dashboard': typeof authAsesorDashboardRoute
  '/user/dashboard': typeof authUserDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/(public)/login': typeof publicLoginRoute
  '/(auth)/admin/dashboard': typeof authAdminDashboardRoute
  '/(auth)/asesor/dashboard': typeof authAsesorDashboardRoute
  '/(auth)/user/dashboard': typeof authUserDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/login'
    | '/admin/dashboard'
    | '/asesor/dashboard'
    | '/user/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/login'
    | '/admin/dashboard'
    | '/asesor/dashboard'
    | '/user/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(public)'
    | '/logout'
    | '/(public)/login'
    | '/(auth)/admin/dashboard'
    | '/(auth)/asesor/dashboard'
    | '/(auth)/user/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/user/dashboard': {
      id: '/(auth)/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof authUserDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/asesor/dashboard': {
      id: '/(auth)/asesor/dashboard'
      path: '/asesor/dashboard'
      fullPath: '/asesor/dashboard'
      preLoaderRoute: typeof authAsesorDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/admin/dashboard': {
      id: '/(auth)/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof authAdminDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authAdminDashboardRoute: typeof authAdminDashboardRoute
  authAsesorDashboardRoute: typeof authAsesorDashboardRoute
  authUserDashboardRoute: typeof authUserDashboardRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAdminDashboardRoute: authAdminDashboardRoute,
  authAsesorDashboardRoute: authAsesorDashboardRoute,
  authUserDashboardRoute: authUserDashboardRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicLoginRoute: typeof publicLoginRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicLoginRoute: publicLoginRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
