
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Action = {
  Upload: 'Upload',
  Delete: 'Delete',
  Update: 'Update',
  Rename: 'Rename',
  Download: 'Download'
} as const

export type Action = (typeof Action)[keyof typeof Action]


export const Level = {
  Admin: 'Admin',
  User: 'User',
  Asesor: 'Asesor'
} as const

export type Level = (typeof Level)[keyof typeof Level]


export const Status = {
  Processing: 'Processing',
  Completed: 'Completed',
  Reprocessing: 'Reprocessing',
  Failed: 'Failed'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const Accreditation = {
  Unggul: 'Unggul',
  Baik_Sekali: 'Baik_Sekali',
  Baik: 'Baik',
  Tidak_Terakreditasi: 'Tidak_Terakreditasi'
} as const

export type Accreditation = (typeof Accreditation)[keyof typeof Accreditation]


export const Provider = {
  OpenAI: 'OpenAI',
  GoogleGenAI: 'GoogleGenAI',
  OpenRouter: 'OpenRouter',
  Nvidia: 'Nvidia',
  Ollama: 'Ollama',
  ZenOpenCode: 'ZenOpenCode'
} as const

export type Provider = (typeof Provider)[keyof typeof Provider]
