
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Users.js'
export type * from './models/MajorAccess.js'
export type * from './models/Majors.js'
export type * from './models/Criteria.js'
export type * from './models/FileLink.js'
export type * from './models/Files.js'
export type * from './models/ActivityLogs.js'
export type * from './commonInputTypes.js'